// <copyright file="LocationsController.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using FortisApi.Standard.Exceptions;
using FortisApi.Standard.Http.Response;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace FortisApi.Standard.Controllers
{
    /// <summary>
    /// LocationsController.
    /// </summary>
    public class LocationsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsController"/> class.
        /// </summary>
        internal LocationsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// LocationsSearch EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="keyword">Optional parameter: You can use any value to search on specific fields of this endpoint results. You can not specify the fields that are used..</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="relationship">Optional parameter: Used to filter the type of locations that will be returned.</param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationSearchsCollection response from the API call.</returns>
        public ApiResponse<Models.ResponseLocationSearchsCollection> LocationsSearch(
                Models.Page1 page = null,
                string keyword = null,
                List<Models.Expand10> expand = null,
                Models.Relationship? relationship = null)
            => CoreHelper.RunTask(LocationsSearchAsync(page, keyword, expand, relationship));

        /// <summary>
        /// LocationsSearch EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="keyword">Optional parameter: You can use any value to search on specific fields of this endpoint results. You can not specify the fields that are used..</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="relationship">Optional parameter: Used to filter the type of locations that will be returned.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationSearchsCollection response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseLocationSearchsCollection>> LocationsSearchAsync(
                Models.Page1 page = null,
                string keyword = null,
                List<Models.Expand10> expand = null,
                Models.Relationship? relationship = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseLocationSearchsCollection>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/location-searches")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("keyword", keyword))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("relationship", (relationship.HasValue) ? CoreHelper.JsonSerialize(relationship.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Listalllocations EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="order"><![CDATA[Optional parameter: Criteria used in query string parameters to order results.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`.  Must be encoded, or use syntax that does not require encoding. >/endpoint?order[0][key]=created_ts&order[0][operator]=asc > >/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] > >/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts", "operator": "asc"}] >.]]></param>
        /// <param name="filterBy"><![CDATA[Optional parameter: Filter criteria that can be used in query string parameters.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`. Must be encoded, or use syntax that does not require encoding. >?filter_by[0][key]=first_name&filter_by[0][operator]==&filter_by[0][value]=Steve > >/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred" }] > >/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value": "VISA" }] > >/endpoint?filter_by=[{ "key": "created_ts", "operator": ">=", "value": "946702799" }, { "key": "created_ts", "operator": "<=", value: "1695061891" }] > >/endpoint?filter_by=[{ "key": "last_name", "operator": "IN", "value": "Williams,Brown,Allman" }] >.]]></param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="format">Optional parameter: Reporting format, valid values: csv, tsv.</param>
        /// <param name="typeahead"><![CDATA[Optional parameter: You can use any `field_name` from this endpoint results to order the list using the value provided as filter for the same `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts with, 3) Contains. >/endpoint?filter={ "field_name": "Value" }&_typeahead=field_name >.]]></param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationsCollection response from the API call.</returns>
        public ApiResponse<Models.ResponseLocationsCollection> Listalllocations(
                Models.Page1 page = null,
                List<Models.Order21> order = null,
                List<Models.FilterBy> filterBy = null,
                List<Models.Expand11> expand = null,
                Models.Format1? format = null,
                string typeahead = null,
                List<Models.Field33> fields = null)
            => CoreHelper.RunTask(ListalllocationsAsync(page, order, filterBy, expand, format, typeahead, fields));

        /// <summary>
        /// Listalllocations EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="order"><![CDATA[Optional parameter: Criteria used in query string parameters to order results.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`.  Must be encoded, or use syntax that does not require encoding. >/endpoint?order[0][key]=created_ts&order[0][operator]=asc > >/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] > >/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts", "operator": "asc"}] >.]]></param>
        /// <param name="filterBy"><![CDATA[Optional parameter: Filter criteria that can be used in query string parameters.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`. Must be encoded, or use syntax that does not require encoding. >?filter_by[0][key]=first_name&filter_by[0][operator]==&filter_by[0][value]=Steve > >/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred" }] > >/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value": "VISA" }] > >/endpoint?filter_by=[{ "key": "created_ts", "operator": ">=", "value": "946702799" }, { "key": "created_ts", "operator": "<=", value: "1695061891" }] > >/endpoint?filter_by=[{ "key": "last_name", "operator": "IN", "value": "Williams,Brown,Allman" }] >.]]></param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="format">Optional parameter: Reporting format, valid values: csv, tsv.</param>
        /// <param name="typeahead"><![CDATA[Optional parameter: You can use any `field_name` from this endpoint results to order the list using the value provided as filter for the same `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts with, 3) Contains. >/endpoint?filter={ "field_name": "Value" }&_typeahead=field_name >.]]></param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationsCollection response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseLocationsCollection>> ListalllocationsAsync(
                Models.Page1 page = null,
                List<Models.Order21> order = null,
                List<Models.FilterBy> filterBy = null,
                List<Models.Expand11> expand = null,
                Models.Format1? format = null,
                string typeahead = null,
                List<Models.Field33> fields = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseLocationsCollection>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/locations")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("order", order))
                      .Query(query => query.Setup("filter_by", filterBy))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("_format", (format.HasValue) ? CoreHelper.JsonSerialize(format.Value).Trim('\"') : null))
                      .Query(query => query.Setup("_typeahead", typeahead))
                      .Query(query => query.Setup("fields", fields?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// LocationsDetail EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="order"><![CDATA[Optional parameter: Criteria used in query string parameters to order results.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`.  Must be encoded, or use syntax that does not require encoding. >/endpoint?order[0][key]=created_ts&order[0][operator]=asc > >/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] > >/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts", "operator": "asc"}] >.]]></param>
        /// <param name="filterBy"><![CDATA[Optional parameter: Filter criteria that can be used in query string parameters.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`. Must be encoded, or use syntax that does not require encoding. >?filter_by[0][key]=first_name&filter_by[0][operator]==&filter_by[0][value]=Steve > >/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred" }] > >/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value": "VISA" }] > >/endpoint?filter_by=[{ "key": "created_ts", "operator": ">=", "value": "946702799" }, { "key": "created_ts", "operator": "<=", value: "1695061891" }] > >/endpoint?filter_by=[{ "key": "last_name", "operator": "IN", "value": "Williams,Brown,Allman" }] >.]]></param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="format">Optional parameter: Reporting format, valid values: csv, tsv.</param>
        /// <param name="typeahead"><![CDATA[Optional parameter: You can use any `field_name` from this endpoint results to order the list using the value provided as filter for the same `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts with, 3) Contains. >/endpoint?filter={ "field_name": "Value" }&_typeahead=field_name >.]]></param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="productTransactionActive">Optional parameter: Product Transaction Active.</param>
        /// <param name="productFileActive">Optional parameter: Product File Active.</param>
        /// <param name="productInvoiceActive">Optional parameter: Product Invoice Active.</param>
        /// <param name="productRecurringActive">Optional parameter: Product Recurring Active.</param>
        /// <param name="productAccountvaultActive">Optional parameter: Product Accountvault Active.</param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationInfosCollection response from the API call.</returns>
        public ApiResponse<Models.ResponseLocationInfosCollection> LocationsDetail(
                Models.Page1 page = null,
                List<Models.Order21> order = null,
                List<Models.FilterBy> filterBy = null,
                List<Models.Expand11> expand = null,
                Models.Format1? format = null,
                string typeahead = null,
                List<Models.Field34> fields = null,
                object productTransactionActive = null,
                object productFileActive = null,
                object productInvoiceActive = null,
                object productRecurringActive = null,
                object productAccountvaultActive = null)
            => CoreHelper.RunTask(LocationsDetailAsync(page, order, filterBy, expand, format, typeahead, fields, productTransactionActive, productFileActive, productInvoiceActive, productRecurringActive, productAccountvaultActive));

        /// <summary>
        /// LocationsDetail EndPoint.
        /// </summary>
        /// <param name="page"><![CDATA[Optional parameter: Use this field to specify paginate your results, by using page size and number. You can use one of the following methods: >/endpoint?page={ "number": 1, "size": 50 } > >/endpoint?page[number]=1&page[size]=50 >.]]></param>
        /// <param name="order"><![CDATA[Optional parameter: Criteria used in query string parameters to order results.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`.  Must be encoded, or use syntax that does not require encoding. >/endpoint?order[0][key]=created_ts&order[0][operator]=asc > >/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] > >/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts", "operator": "asc"}] >.]]></param>
        /// <param name="filterBy"><![CDATA[Optional parameter: Filter criteria that can be used in query string parameters.  Most fields from the endpoint results can be used as a `key`.  Unsupported fields or operators will return a `412`. Must be encoded, or use syntax that does not require encoding. >?filter_by[0][key]=first_name&filter_by[0][operator]==&filter_by[0][value]=Steve > >/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred" }] > >/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value": "VISA" }] > >/endpoint?filter_by=[{ "key": "created_ts", "operator": ">=", "value": "946702799" }, { "key": "created_ts", "operator": "<=", value: "1695061891" }] > >/endpoint?filter_by=[{ "key": "last_name", "operator": "IN", "value": "Williams,Brown,Allman" }] >.]]></param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="format">Optional parameter: Reporting format, valid values: csv, tsv.</param>
        /// <param name="typeahead"><![CDATA[Optional parameter: You can use any `field_name` from this endpoint results to order the list using the value provided as filter for the same `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts with, 3) Contains. >/endpoint?filter={ "field_name": "Value" }&_typeahead=field_name >.]]></param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="productTransactionActive">Optional parameter: Product Transaction Active.</param>
        /// <param name="productFileActive">Optional parameter: Product File Active.</param>
        /// <param name="productInvoiceActive">Optional parameter: Product Invoice Active.</param>
        /// <param name="productRecurringActive">Optional parameter: Product Recurring Active.</param>
        /// <param name="productAccountvaultActive">Optional parameter: Product Accountvault Active.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationInfosCollection response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseLocationInfosCollection>> LocationsDetailAsync(
                Models.Page1 page = null,
                List<Models.Order21> order = null,
                List<Models.FilterBy> filterBy = null,
                List<Models.Expand11> expand = null,
                Models.Format1? format = null,
                string typeahead = null,
                List<Models.Field34> fields = null,
                object productTransactionActive = null,
                object productFileActive = null,
                object productInvoiceActive = null,
                object productRecurringActive = null,
                object productAccountvaultActive = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseLocationInfosCollection>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/locations/info")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("order", order))
                      .Query(query => query.Setup("filter_by", filterBy))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("_format", (format.HasValue) ? CoreHelper.JsonSerialize(format.Value).Trim('\"') : null))
                      .Query(query => query.Setup("_typeahead", typeahead))
                      .Query(query => query.Setup("fields", fields?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("product_transaction_active", productTransactionActive))
                      .Query(query => query.Setup("product_file_active", productFileActive))
                      .Query(query => query.Setup("product_invoice_active", productInvoiceActive))
                      .Query(query => query.Setup("product_recurring_active", productRecurringActive))
                      .Query(query => query.Setup("product_accountvault_active", productAccountvaultActive))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Viewsinglelocationrecord EndPoint.
        /// </summary>
        /// <param name="locationId">Required parameter: Location ID.</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocation response from the API call.</returns>
        public ApiResponse<Models.ResponseLocation> Viewsinglelocationrecord(
                string locationId,
                List<Models.Expand11> expand = null,
                List<Models.Field35> fields = null)
            => CoreHelper.RunTask(ViewsinglelocationrecordAsync(locationId, expand, fields));

        /// <summary>
        /// Viewsinglelocationrecord EndPoint.
        /// </summary>
        /// <param name="locationId">Required parameter: Location ID.</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocation response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseLocation>> ViewsinglelocationrecordAsync(
                string locationId,
                List<Models.Expand11> expand = null,
                List<Models.Field35> fields = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseLocation>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/locations/{location_id}")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("location_id", locationId).Required())
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("fields", fields?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// LocationDetail EndPoint.
        /// </summary>
        /// <param name="locationId">Required parameter: Location ID.</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="productTransactionActive">Optional parameter: Product Transaction Active.</param>
        /// <param name="productFileActive">Optional parameter: Product File Active.</param>
        /// <param name="productInvoiceActive">Optional parameter: Product Invoice Active.</param>
        /// <param name="productRecurringActive">Optional parameter: Product Recurring Active.</param>
        /// <param name="productAccountvaultActive">Optional parameter: Product Accountvault Active.</param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationInfo response from the API call.</returns>
        public ApiResponse<Models.ResponseLocationInfo> LocationDetail(
                string locationId,
                List<Models.Expand11> expand = null,
                List<Models.Field36> fields = null,
                object productTransactionActive = null,
                object productFileActive = null,
                object productInvoiceActive = null,
                object productRecurringActive = null,
                object productAccountvaultActive = null)
            => CoreHelper.RunTask(LocationDetailAsync(locationId, expand, fields, productTransactionActive, productFileActive, productInvoiceActive, productRecurringActive, productAccountvaultActive));

        /// <summary>
        /// LocationDetail EndPoint.
        /// </summary>
        /// <param name="locationId">Required parameter: Location ID.</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="fields">Optional parameter: You can use any `field_name` from this endpoint results to filter the list of fields returned on the response..</param>
        /// <param name="productTransactionActive">Optional parameter: Product Transaction Active.</param>
        /// <param name="productFileActive">Optional parameter: Product File Active.</param>
        /// <param name="productInvoiceActive">Optional parameter: Product Invoice Active.</param>
        /// <param name="productRecurringActive">Optional parameter: Product Recurring Active.</param>
        /// <param name="productAccountvaultActive">Optional parameter: Product Accountvault Active.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseLocationInfo response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseLocationInfo>> LocationDetailAsync(
                string locationId,
                List<Models.Expand11> expand = null,
                List<Models.Field36> fields = null,
                object productTransactionActive = null,
                object productFileActive = null,
                object productInvoiceActive = null,
                object productRecurringActive = null,
                object productAccountvaultActive = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseLocationInfo>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/locations/{location_id}/info")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("location_id", locationId).Required())
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("fields", fields?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))
                      .Query(query => query.Setup("product_transaction_active", productTransactionActive))
                      .Query(query => query.Setup("product_file_active", productFileActive))
                      .Query(query => query.Setup("product_invoice_active", productInvoiceActive))
                      .Query(query => query.Setup("product_recurring_active", productRecurringActive))
                      .Query(query => query.Setup("product_accountvault_active", productAccountvaultActive))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}