// <copyright file="TransactionsAchController.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using FortisApi.Standard.Exceptions;
using FortisApi.Standard.Http.Response;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace FortisApi.Standard.Controllers
{
    /// <summary>
    /// TransactionsAchController.
    /// </summary>
    public class TransactionsAchController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsAchController"/> class.
        /// </summary>
        internal TransactionsAchController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// ACH Transaction that is intended for a Blind Refund, where a previous transaction id is not known. Must have Fortis approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchCredit(
                Models.V1TransactionsAchCreditKeyedRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchCreditAsync(body, expand));

        /// <summary>
        /// ACH Transaction that is intended for a Blind Refund, where a previous transaction id is not known. Must have Fortis approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchCreditAsync(
                Models.V1TransactionsAchCreditKeyedRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/credit/keyed")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// ACH Transaction that is intended for a Blind Refund, where using a previous transaction id to re process. Must have Fortis approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchCreditPreviousTransaction(
                Models.V1TransactionsAchCreditPrevTrxnRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchCreditPreviousTransactionAsync(body, expand));

        /// <summary>
        /// ACH Transaction that is intended for a Blind Refund, where using a previous transaction id to re process. Must have Fortis approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchCreditPreviousTransactionAsync(
                Models.V1TransactionsAchCreditPrevTrxnRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/credit/prev-trxn")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// ACH Transaction using an ACH Token_id that is intended for a Blind Refund, where a previous transaction id is not known. Must have approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchCreditTokenized(
                Models.V1TransactionsAchCreditTokenRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchCreditTokenizedAsync(body, expand));

        /// <summary>
        /// ACH Transaction using an ACH Token_id that is intended for a Blind Refund, where a previous transaction id is not known. Must have approval prior to use.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchCreditTokenizedAsync(
                Models.V1TransactionsAchCreditTokenRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/credit/token")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Creates an ACH Sale transaction to debit the customers bank account.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchDebit(
                Models.V1TransactionsAchDebitKeyedRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchDebitAsync(body, expand));

        /// <summary>
        /// Creates an ACH Sale transaction to debit the customers bank account.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchDebitAsync(
                Models.V1TransactionsAchDebitKeyedRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/debit/keyed")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Create an ACH Sale transaction with a previous ACH transaction_id.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchDebitPreviousTransaction(
                Models.V1TransactionsAchDebitPrevTrxnRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchDebitPreviousTransactionAsync(body, expand));

        /// <summary>
        /// Create an ACH Sale transaction with a previous ACH transaction_id.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchDebitPreviousTransactionAsync(
                Models.V1TransactionsAchDebitPrevTrxnRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/debit/prev-trxn")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Utilize an ACH Token_id previously created to process an ACH Sale transaction.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchDebitTokenized(
                Models.V1TransactionsAchDebitTokenRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchDebitTokenizedAsync(body, expand));

        /// <summary>
        /// Utilize an ACH Token_id previously created to process an ACH Sale transaction.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchDebitTokenizedAsync(
                Models.V1TransactionsAchDebitTokenRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/debit/token")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Create a new ACH refund transaction using previous transaction id.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public ApiResponse<Models.ResponseTransaction> AchRefundPreviousTransaction(
                Models.V1TransactionsAchRefundPrevTrxnRequest body,
                List<Models.Expand60> expand = null)
            => CoreHelper.RunTask(AchRefundPreviousTransactionAsync(body, expand));

        /// <summary>
        /// Create a new ACH refund transaction using previous transaction id.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="expand">Optional parameter: Most endpoints in the API have a way to retrieve extra data related to the current record being retrieved. For example, if the API request is for the accountvaults endpoint, and the end user also needs to know which contact the token belongs to, this data can be returned in the accountvaults endpoint request..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ResponseTransaction response from the API call.</returns>
        public async Task<ApiResponse<Models.ResponseTransaction>> AchRefundPreviousTransactionAsync(
                Models.V1TransactionsAchRefundPrevTrxnRequest body,
                List<Models.Expand60> expand = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ResponseTransaction>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/transactions/ach/refund/prev-trxn")
                  .WithAndAuth(andAuth => andAuth
                      .Add("user-id")
                      .Add("user-api-key")
                      .Add("developer-id")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Query(query => query.Setup("expand", expand?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new Response401TokenException(errorReason, context)))
                  .ErrorCase("412", CreateErrorCase("Precondition Failed", (errorReason, context) => new Response412Exception(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}