// <copyright file="AchSecCode3.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// AchSecCode3.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum AchSecCode3
    {
        /// <summary>
        /// Web.
        /// </summary>
        [EnumMember(Value = "WEB")]
        Web,

        /// <summary>
        /// Ccd.
        /// </summary>
        [EnumMember(Value = "CCD")]
        Ccd,

        /// <summary>
        /// Ppd.
        /// </summary>
        [EnumMember(Value = "PPD")]
        Ppd,

        /// <summary>
        /// C21.
        /// </summary>
        [EnumMember(Value = "C21")]
        C21,

        /// <summary>
        /// Pop.
        /// </summary>
        [EnumMember(Value = "POP")]
        Pop,

        /// <summary>
        /// Tel.
        /// </summary>
        [EnumMember(Value = "TEL")]
        Tel,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}