// <copyright file="CauSummaryStatusId.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// CauSummaryStatusId.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<NumberEnumConverter>), nameof(_Unknown))]
    public enum CauSummaryStatusId
    {
        /// <summary>
        /// Enum0.
        /// </summary>
        Enum0 = 0,

        /// <summary>
        /// Enum1.
        /// </summary>
        Enum1 = 1,

        /// <summary>
        /// Enum2.
        /// </summary>
        Enum2 = 2,

        /// <summary>
        /// Enum3.
        /// </summary>
        Enum3 = 3,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}