// <copyright file="Children.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Children.
    /// </summary>
    public class Children
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountNumber;
        private string contactApiId;
        private string firstName;
        private string cellPhone;
        private double? balance;
        private string companyName;
        private string headerMessage;
        private string dateOfBirth;
        private string homePhone;
        private string officePhone;
        private string officePhoneExt;
        private string homePhoneCountryCode;
        private string officePhoneCountryCode;
        private string cellPhoneCountryCode;
        private string contactC1;
        private string contactC2;
        private string contactC3;
        private string parentId;
        private string email;
        private string tokenImportId;
        private string createdUserId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_number", false },
            { "contact_api_id", false },
            { "first_name", false },
            { "cell_phone", false },
            { "balance", false },
            { "company_name", false },
            { "header_message", false },
            { "date_of_birth", false },
            { "home_phone", false },
            { "office_phone", false },
            { "office_phone_ext", false },
            { "home_phone_country_code", false },
            { "office_phone_country_code", false },
            { "cell_phone_country_code", false },
            { "contact_c1", false },
            { "contact_c2", false },
            { "contact_c3", false },
            { "parent_id", false },
            { "email", false },
            { "token_import_id", false },
            { "created_user_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Children"/> class.
        /// </summary>
        public Children()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Children"/> class.
        /// </summary>
        /// <param name="locationId">location_id.</param>
        /// <param name="accountNumber">account_number.</param>
        /// <param name="contactApiId">contact_api_id.</param>
        /// <param name="firstName">first_name.</param>
        /// <param name="lastName">last_name.</param>
        /// <param name="cellPhone">cell_phone.</param>
        /// <param name="balance">balance.</param>
        /// <param name="address">address.</param>
        /// <param name="companyName">company_name.</param>
        /// <param name="headerMessage">header_message.</param>
        /// <param name="dateOfBirth">date_of_birth.</param>
        /// <param name="emailTrxReceipt">email_trx_receipt.</param>
        /// <param name="homePhone">home_phone.</param>
        /// <param name="officePhone">office_phone.</param>
        /// <param name="officePhoneExt">office_phone_ext.</param>
        /// <param name="homePhoneCountryCode">home_phone_country_code.</param>
        /// <param name="officePhoneCountryCode">office_phone_country_code.</param>
        /// <param name="cellPhoneCountryCode">cell_phone_country_code.</param>
        /// <param name="headerMessageType">header_message_type.</param>
        /// <param name="updateIfExists">update_if_exists.</param>
        /// <param name="contactC1">contact_c1.</param>
        /// <param name="contactC2">contact_c2.</param>
        /// <param name="contactC3">contact_c3.</param>
        /// <param name="parentId">parent_id.</param>
        /// <param name="email">email.</param>
        /// <param name="tokenImportId">token_import_id.</param>
        /// <param name="id">id.</param>
        /// <param name="createdTs">created_ts.</param>
        /// <param name="modifiedTs">modified_ts.</param>
        /// <param name="active">active.</param>
        /// <param name="createdUserId">created_user_id.</param>
        public Children(
            string locationId = null,
            string accountNumber = null,
            string contactApiId = null,
            string firstName = null,
            string lastName = null,
            string cellPhone = null,
            double? balance = null,
            Models.Address4 address = null,
            string companyName = null,
            string headerMessage = null,
            string dateOfBirth = null,
            bool? emailTrxReceipt = null,
            string homePhone = null,
            string officePhone = null,
            string officePhoneExt = null,
            string homePhoneCountryCode = null,
            string officePhoneCountryCode = null,
            string cellPhoneCountryCode = null,
            int? headerMessageType = null,
            object updateIfExists = null,
            string contactC1 = null,
            string contactC2 = null,
            string contactC3 = null,
            string parentId = null,
            string email = null,
            string tokenImportId = null,
            string id = null,
            int? createdTs = null,
            int? modifiedTs = null,
            bool? active = null,
            string createdUserId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.LocationId = locationId;

            if (accountNumber != null)
            {
                this.AccountNumber = accountNumber;
            }

            if (contactApiId != null)
            {
                this.ContactApiId = contactApiId;
            }

            if (firstName != null)
            {
                this.FirstName = firstName;
            }
            this.LastName = lastName;

            if (cellPhone != null)
            {
                this.CellPhone = cellPhone;
            }

            if (balance != null)
            {
                this.Balance = balance;
            }
            this.Address = address;

            if (companyName != null)
            {
                this.CompanyName = companyName;
            }

            if (headerMessage != null)
            {
                this.HeaderMessage = headerMessage;
            }

            if (dateOfBirth != null)
            {
                this.DateOfBirth = dateOfBirth;
            }
            this.EmailTrxReceipt = emailTrxReceipt;

            if (homePhone != null)
            {
                this.HomePhone = homePhone;
            }

            if (officePhone != null)
            {
                this.OfficePhone = officePhone;
            }

            if (officePhoneExt != null)
            {
                this.OfficePhoneExt = officePhoneExt;
            }

            if (homePhoneCountryCode != null)
            {
                this.HomePhoneCountryCode = homePhoneCountryCode;
            }

            if (officePhoneCountryCode != null)
            {
                this.OfficePhoneCountryCode = officePhoneCountryCode;
            }

            if (cellPhoneCountryCode != null)
            {
                this.CellPhoneCountryCode = cellPhoneCountryCode;
            }
            this.HeaderMessageType = headerMessageType;
            this.UpdateIfExists = updateIfExists;

            if (contactC1 != null)
            {
                this.ContactC1 = contactC1;
            }

            if (contactC2 != null)
            {
                this.ContactC2 = contactC2;
            }

            if (contactC3 != null)
            {
                this.ContactC3 = contactC3;
            }

            if (parentId != null)
            {
                this.ParentId = parentId;
            }

            if (email != null)
            {
                this.Email = email;
            }

            if (tokenImportId != null)
            {
                this.TokenImportId = tokenImportId;
            }
            this.Id = id;
            this.CreatedTs = createdTs;
            this.ModifiedTs = modifiedTs;
            this.Active = active;

            if (createdUserId != null)
            {
                this.CreatedUserId = createdUserId;
            }
        }

        /// <summary>
        /// Location ID
        /// </summary>
        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationId { get; set; }

        /// <summary>
        /// Contact Account Number
        /// </summary>
        [JsonProperty("account_number")]
        public string AccountNumber
        {
            get
            {
                return this.accountNumber;
            }

            set
            {
                this.shouldSerialize["account_number"] = true;
                this.accountNumber = value;
            }
        }

        /// <summary>
        /// Contact API Id
        /// </summary>
        [JsonProperty("contact_api_id")]
        public string ContactApiId
        {
            get
            {
                return this.contactApiId;
            }

            set
            {
                this.shouldSerialize["contact_api_id"] = true;
                this.contactApiId = value;
            }
        }

        /// <summary>
        /// First Name
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName
        {
            get
            {
                return this.firstName;
            }

            set
            {
                this.shouldSerialize["first_name"] = true;
                this.firstName = value;
            }
        }

        /// <summary>
        /// Last Name
        /// </summary>
        [JsonProperty("last_name", NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }

        /// <summary>
        /// Cell phone of contact
        /// </summary>
        [JsonProperty("cell_phone")]
        public string CellPhone
        {
            get
            {
                return this.cellPhone;
            }

            set
            {
                this.shouldSerialize["cell_phone"] = true;
                this.cellPhone = value;
            }
        }

        /// <summary>
        /// Balance
        /// </summary>
        [JsonProperty("balance")]
        public double? Balance
        {
            get
            {
                return this.balance;
            }

            set
            {
                this.shouldSerialize["balance"] = true;
                this.balance = value;
            }
        }

        /// <summary>
        /// Gets or sets Address.
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Address4 Address { get; set; }

        /// <summary>
        /// Company Name
        /// </summary>
        [JsonProperty("company_name")]
        public string CompanyName
        {
            get
            {
                return this.companyName;
            }

            set
            {
                this.shouldSerialize["company_name"] = true;
                this.companyName = value;
            }
        }

        /// <summary>
        /// Header Message
        /// </summary>
        [JsonProperty("header_message")]
        public string HeaderMessage
        {
            get
            {
                return this.headerMessage;
            }

            set
            {
                this.shouldSerialize["header_message"] = true;
                this.headerMessage = value;
            }
        }

        /// <summary>
        /// Contacts DOB, Format: yyyy-MM-dd
        /// </summary>
        [JsonProperty("date_of_birth")]
        public string DateOfBirth
        {
            get
            {
                return this.dateOfBirth;
            }

            set
            {
                this.shouldSerialize["date_of_birth"] = true;
                this.dateOfBirth = value;
            }
        }

        /// <summary>
        /// Whether or not to email all transactions receipts to contact (1 or 0)
        /// </summary>
        [JsonProperty("email_trx_receipt", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EmailTrxReceipt { get; set; }

        /// <summary>
        /// Contacts home phone
        /// </summary>
        [JsonProperty("home_phone")]
        public string HomePhone
        {
            get
            {
                return this.homePhone;
            }

            set
            {
                this.shouldSerialize["home_phone"] = true;
                this.homePhone = value;
            }
        }

        /// <summary>
        /// Contacts office phone
        /// </summary>
        [JsonProperty("office_phone")]
        public string OfficePhone
        {
            get
            {
                return this.officePhone;
            }

            set
            {
                this.shouldSerialize["office_phone"] = true;
                this.officePhone = value;
            }
        }

        /// <summary>
        /// Contacts office phone extension for office phone
        /// </summary>
        [JsonProperty("office_phone_ext")]
        public string OfficePhoneExt
        {
            get
            {
                return this.officePhoneExt;
            }

            set
            {
                this.shouldSerialize["office_phone_ext"] = true;
                this.officePhoneExt = value;
            }
        }

        /// <summary>
        /// Home phone country code
        /// </summary>
        [JsonProperty("home_phone_country_code")]
        public string HomePhoneCountryCode
        {
            get
            {
                return this.homePhoneCountryCode;
            }

            set
            {
                this.shouldSerialize["home_phone_country_code"] = true;
                this.homePhoneCountryCode = value;
            }
        }

        /// <summary>
        /// Office phone country code
        /// </summary>
        [JsonProperty("office_phone_country_code")]
        public string OfficePhoneCountryCode
        {
            get
            {
                return this.officePhoneCountryCode;
            }

            set
            {
                this.shouldSerialize["office_phone_country_code"] = true;
                this.officePhoneCountryCode = value;
            }
        }

        /// <summary>
        /// Cell phone country code
        /// </summary>
        [JsonProperty("cell_phone_country_code")]
        public string CellPhoneCountryCode
        {
            get
            {
                return this.cellPhoneCountryCode;
            }

            set
            {
                this.shouldSerialize["cell_phone_country_code"] = true;
                this.cellPhoneCountryCode = value;
            }
        }

        /// <summary>
        /// Header Message Type
        /// </summary>
        [JsonProperty("header_message_type", NullValueHandling = NullValueHandling.Ignore)]
        public int? HeaderMessageType { get; set; }

        /// <summary>
        /// Gets or sets UpdateIfExists.
        /// </summary>
        [JsonProperty("update_if_exists", NullValueHandling = NullValueHandling.Ignore)]
        public object UpdateIfExists { get; set; }

        /// <summary>
        /// Custom field 1 for api users to store custom data
        /// </summary>
        [JsonProperty("contact_c1")]
        public string ContactC1
        {
            get
            {
                return this.contactC1;
            }

            set
            {
                this.shouldSerialize["contact_c1"] = true;
                this.contactC1 = value;
            }
        }

        /// <summary>
        /// Custom field 2 for api users to store custom data
        /// </summary>
        [JsonProperty("contact_c2")]
        public string ContactC2
        {
            get
            {
                return this.contactC2;
            }

            set
            {
                this.shouldSerialize["contact_c2"] = true;
                this.contactC2 = value;
            }
        }

        /// <summary>
        /// Custom field 3 for api users to store custom data
        /// </summary>
        [JsonProperty("contact_c3")]
        public string ContactC3
        {
            get
            {
                return this.contactC3;
            }

            set
            {
                this.shouldSerialize["contact_c3"] = true;
                this.contactC3 = value;
            }
        }

        /// <summary>
        /// Parent Id
        /// </summary>
        [JsonProperty("parent_id")]
        public string ParentId
        {
            get
            {
                return this.parentId;
            }

            set
            {
                this.shouldSerialize["parent_id"] = true;
                this.parentId = value;
            }
        }

        /// <summary>
        /// Email of contact
        /// </summary>
        [JsonProperty("email")]
        public string Email
        {
            get
            {
                return this.email;
            }

            set
            {
                this.shouldSerialize["email"] = true;
                this.email = value;
            }
        }

        /// <summary>
        /// Token Import Id
        /// </summary>
        [JsonProperty("token_import_id")]
        public string TokenImportId
        {
            get
            {
                return this.tokenImportId;
            }

            set
            {
                this.shouldSerialize["token_import_id"] = true;
                this.tokenImportId = value;
            }
        }

        /// <summary>
        /// Contact ID
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Created Time Stamp
        /// </summary>
        [JsonProperty("created_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? CreatedTs { get; set; }

        /// <summary>
        /// Modified Time Stamp
        /// </summary>
        [JsonProperty("modified_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? ModifiedTs { get; set; }

        /// <summary>
        /// Active
        /// </summary>
        [JsonProperty("active", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Active { get; set; }

        /// <summary>
        /// User ID Created the register
        /// </summary>
        [JsonProperty("created_user_id")]
        public string CreatedUserId
        {
            get
            {
                return this.createdUserId;
            }

            set
            {
                this.shouldSerialize["created_user_id"] = true;
                this.createdUserId = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Children : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountNumber()
        {
            this.shouldSerialize["account_number"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContactApiId()
        {
            this.shouldSerialize["contact_api_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFirstName()
        {
            this.shouldSerialize["first_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCellPhone()
        {
            this.shouldSerialize["cell_phone"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetBalance()
        {
            this.shouldSerialize["balance"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCompanyName()
        {
            this.shouldSerialize["company_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetHeaderMessage()
        {
            this.shouldSerialize["header_message"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateOfBirth()
        {
            this.shouldSerialize["date_of_birth"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetHomePhone()
        {
            this.shouldSerialize["home_phone"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOfficePhone()
        {
            this.shouldSerialize["office_phone"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOfficePhoneExt()
        {
            this.shouldSerialize["office_phone_ext"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetHomePhoneCountryCode()
        {
            this.shouldSerialize["home_phone_country_code"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOfficePhoneCountryCode()
        {
            this.shouldSerialize["office_phone_country_code"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCellPhoneCountryCode()
        {
            this.shouldSerialize["cell_phone_country_code"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContactC1()
        {
            this.shouldSerialize["contact_c1"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContactC2()
        {
            this.shouldSerialize["contact_c2"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetContactC3()
        {
            this.shouldSerialize["contact_c3"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetParentId()
        {
            this.shouldSerialize["parent_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEmail()
        {
            this.shouldSerialize["email"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTokenImportId()
        {
            this.shouldSerialize["token_import_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCreatedUserId()
        {
            this.shouldSerialize["created_user_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountNumber()
        {
            return this.shouldSerialize["account_number"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContactApiId()
        {
            return this.shouldSerialize["contact_api_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFirstName()
        {
            return this.shouldSerialize["first_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCellPhone()
        {
            return this.shouldSerialize["cell_phone"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeBalance()
        {
            return this.shouldSerialize["balance"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCompanyName()
        {
            return this.shouldSerialize["company_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeHeaderMessage()
        {
            return this.shouldSerialize["header_message"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateOfBirth()
        {
            return this.shouldSerialize["date_of_birth"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeHomePhone()
        {
            return this.shouldSerialize["home_phone"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOfficePhone()
        {
            return this.shouldSerialize["office_phone"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOfficePhoneExt()
        {
            return this.shouldSerialize["office_phone_ext"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeHomePhoneCountryCode()
        {
            return this.shouldSerialize["home_phone_country_code"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOfficePhoneCountryCode()
        {
            return this.shouldSerialize["office_phone_country_code"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCellPhoneCountryCode()
        {
            return this.shouldSerialize["cell_phone_country_code"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContactC1()
        {
            return this.shouldSerialize["contact_c1"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContactC2()
        {
            return this.shouldSerialize["contact_c2"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeContactC3()
        {
            return this.shouldSerialize["contact_c3"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeParentId()
        {
            return this.shouldSerialize["parent_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEmail()
        {
            return this.shouldSerialize["email"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTokenImportId()
        {
            return this.shouldSerialize["token_import_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCreatedUserId()
        {
            return this.shouldSerialize["created_user_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Children other &&
                (this.LocationId == null && other.LocationId == null ||
                 this.LocationId?.Equals(other.LocationId) == true) &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.ContactApiId == null && other.ContactApiId == null ||
                 this.ContactApiId?.Equals(other.ContactApiId) == true) &&
                (this.FirstName == null && other.FirstName == null ||
                 this.FirstName?.Equals(other.FirstName) == true) &&
                (this.LastName == null && other.LastName == null ||
                 this.LastName?.Equals(other.LastName) == true) &&
                (this.CellPhone == null && other.CellPhone == null ||
                 this.CellPhone?.Equals(other.CellPhone) == true) &&
                (this.Balance == null && other.Balance == null ||
                 this.Balance?.Equals(other.Balance) == true) &&
                (this.Address == null && other.Address == null ||
                 this.Address?.Equals(other.Address) == true) &&
                (this.CompanyName == null && other.CompanyName == null ||
                 this.CompanyName?.Equals(other.CompanyName) == true) &&
                (this.HeaderMessage == null && other.HeaderMessage == null ||
                 this.HeaderMessage?.Equals(other.HeaderMessage) == true) &&
                (this.DateOfBirth == null && other.DateOfBirth == null ||
                 this.DateOfBirth?.Equals(other.DateOfBirth) == true) &&
                (this.EmailTrxReceipt == null && other.EmailTrxReceipt == null ||
                 this.EmailTrxReceipt?.Equals(other.EmailTrxReceipt) == true) &&
                (this.HomePhone == null && other.HomePhone == null ||
                 this.HomePhone?.Equals(other.HomePhone) == true) &&
                (this.OfficePhone == null && other.OfficePhone == null ||
                 this.OfficePhone?.Equals(other.OfficePhone) == true) &&
                (this.OfficePhoneExt == null && other.OfficePhoneExt == null ||
                 this.OfficePhoneExt?.Equals(other.OfficePhoneExt) == true) &&
                (this.HomePhoneCountryCode == null && other.HomePhoneCountryCode == null ||
                 this.HomePhoneCountryCode?.Equals(other.HomePhoneCountryCode) == true) &&
                (this.OfficePhoneCountryCode == null && other.OfficePhoneCountryCode == null ||
                 this.OfficePhoneCountryCode?.Equals(other.OfficePhoneCountryCode) == true) &&
                (this.CellPhoneCountryCode == null && other.CellPhoneCountryCode == null ||
                 this.CellPhoneCountryCode?.Equals(other.CellPhoneCountryCode) == true) &&
                (this.HeaderMessageType == null && other.HeaderMessageType == null ||
                 this.HeaderMessageType?.Equals(other.HeaderMessageType) == true) &&
                (this.UpdateIfExists == null && other.UpdateIfExists == null ||
                 this.UpdateIfExists?.Equals(other.UpdateIfExists) == true) &&
                (this.ContactC1 == null && other.ContactC1 == null ||
                 this.ContactC1?.Equals(other.ContactC1) == true) &&
                (this.ContactC2 == null && other.ContactC2 == null ||
                 this.ContactC2?.Equals(other.ContactC2) == true) &&
                (this.ContactC3 == null && other.ContactC3 == null ||
                 this.ContactC3?.Equals(other.ContactC3) == true) &&
                (this.ParentId == null && other.ParentId == null ||
                 this.ParentId?.Equals(other.ParentId) == true) &&
                (this.Email == null && other.Email == null ||
                 this.Email?.Equals(other.Email) == true) &&
                (this.TokenImportId == null && other.TokenImportId == null ||
                 this.TokenImportId?.Equals(other.TokenImportId) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                (this.ModifiedTs == null && other.ModifiedTs == null ||
                 this.ModifiedTs?.Equals(other.ModifiedTs) == true) &&
                (this.Active == null && other.Active == null ||
                 this.Active?.Equals(other.Active) == true) &&
                (this.CreatedUserId == null && other.CreatedUserId == null ||
                 this.CreatedUserId?.Equals(other.CreatedUserId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"LocationId = {this.LocationId ?? "null"}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"ContactApiId = {this.ContactApiId ?? "null"}");
            toStringOutput.Add($"FirstName = {this.FirstName ?? "null"}");
            toStringOutput.Add($"LastName = {this.LastName ?? "null"}");
            toStringOutput.Add($"CellPhone = {this.CellPhone ?? "null"}");
            toStringOutput.Add($"Balance = {(this.Balance == null ? "null" : this.Balance.ToString())}");
            toStringOutput.Add($"Address = {(this.Address == null ? "null" : this.Address.ToString())}");
            toStringOutput.Add($"CompanyName = {this.CompanyName ?? "null"}");
            toStringOutput.Add($"HeaderMessage = {this.HeaderMessage ?? "null"}");
            toStringOutput.Add($"DateOfBirth = {this.DateOfBirth ?? "null"}");
            toStringOutput.Add($"EmailTrxReceipt = {(this.EmailTrxReceipt == null ? "null" : this.EmailTrxReceipt.ToString())}");
            toStringOutput.Add($"HomePhone = {this.HomePhone ?? "null"}");
            toStringOutput.Add($"OfficePhone = {this.OfficePhone ?? "null"}");
            toStringOutput.Add($"OfficePhoneExt = {this.OfficePhoneExt ?? "null"}");
            toStringOutput.Add($"HomePhoneCountryCode = {this.HomePhoneCountryCode ?? "null"}");
            toStringOutput.Add($"OfficePhoneCountryCode = {this.OfficePhoneCountryCode ?? "null"}");
            toStringOutput.Add($"CellPhoneCountryCode = {this.CellPhoneCountryCode ?? "null"}");
            toStringOutput.Add($"HeaderMessageType = {(this.HeaderMessageType == null ? "null" : this.HeaderMessageType.ToString())}");
            toStringOutput.Add($"UpdateIfExists = {(this.UpdateIfExists == null ? "null" : this.UpdateIfExists.ToString())}");
            toStringOutput.Add($"ContactC1 = {this.ContactC1 ?? "null"}");
            toStringOutput.Add($"ContactC2 = {this.ContactC2 ?? "null"}");
            toStringOutput.Add($"ContactC3 = {this.ContactC3 ?? "null"}");
            toStringOutput.Add($"ParentId = {this.ParentId ?? "null"}");
            toStringOutput.Add($"Email = {this.Email ?? "null"}");
            toStringOutput.Add($"TokenImportId = {this.TokenImportId ?? "null"}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");
            toStringOutput.Add($"ModifiedTs = {(this.ModifiedTs == null ? "null" : this.ModifiedTs.ToString())}");
            toStringOutput.Add($"Active = {(this.Active == null ? "null" : this.Active.ToString())}");
            toStringOutput.Add($"CreatedUserId = {this.CreatedUserId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}