// <copyright file="Conditions42.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Conditions42.
    /// </summary>
    public class Conditions42 : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Conditions42"/> class.
        /// </summary>
        public Conditions42()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Conditions42"/> class.
        /// </summary>
        /// <param name="method">method.</param>
        /// <param name="values">values.</param>
        public Conditions42(
            Models.Method5Enum? method = null,
            Models.Values6Enum? values = null)
        {
            this.Method = method;
            this.Values = values;
        }

        /// <summary>
        /// Gets or sets Method.
        /// </summary>
        [JsonProperty("method", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Method5Enum? Method { get; set; }

        /// <summary>
        /// Gets or sets Values.
        /// </summary>
        [JsonProperty("values", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Values6Enum? Values { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Conditions42 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Conditions42 other &&
                (this.Method == null && other.Method == null ||
                 this.Method?.Equals(other.Method) == true) &&
                (this.Values == null && other.Values == null ||
                 this.Values?.Equals(other.Values) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Method = {(this.Method == null ? "null" : this.Method.ToString())}");
            toStringOutput.Add($"Values = {(this.Values == null ? "null" : this.Values.ToString())}");

            base.ToString(toStringOutput);
        }
    }
}