// <copyright file="ContactUserDefaultEntryPage.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// ContactUserDefaultEntryPage.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum ContactUserDefaultEntryPage
    {
        /// <summary>
        /// Dashboard.
        /// </summary>
        [EnumMember(Value = "dashboard")]
        Dashboard,

        /// <summary>
        /// Makepayment.
        /// </summary>
        [EnumMember(Value = "makepayment")]
        Makepayment,

        /// <summary>
        /// Paymenthistory.
        /// </summary>
        [EnumMember(Value = "paymenthistory")]
        Paymenthistory,

        /// <summary>
        /// Accounts.
        /// </summary>
        [EnumMember(Value = "accounts")]
        Accounts,

        /// <summary>
        /// Recurrings.
        /// </summary>
        [EnumMember(Value = "recurrings")]
        Recurrings,

        /// <summary>
        /// Invoices.
        /// </summary>
        [EnumMember(Value = "invoices")]
        Invoices,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}