// <copyright file="Data38.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Data38.
    /// </summary>
    public class Data38 : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Data38"/> class.
        /// </summary>
        public Data38()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Data38"/> class.
        /// </summary>
        /// <param name="resultCode">resultCode.</param>
        /// <param name="merchantID">merchantID.</param>
        /// <param name="applePay">applePay.</param>
        /// <param name="googlePay">googlePay.</param>
        /// <param name="applePayDomains">applePayDomains.</param>
        /// <param name="message">message.</param>
        /// <param name="googleJWT">googleJWT.</param>
        public Data38(
            bool? resultCode = null,
            string merchantID = null,
            bool? applePay = null,
            bool? googlePay = null,
            object applePayDomains = null,
            string message = null,
            string googleJWT = null)
        {
            this.ResultCode = resultCode;
            this.MerchantID = merchantID;
            this.ApplePay = applePay;
            this.GooglePay = googlePay;
            this.ApplePayDomains = applePayDomains;
            this.Message = message;
            this.GoogleJWT = googleJWT;
        }

        /// <summary>
        /// 0 for success, 1 for error. More details on Message field.
        /// </summary>
        [JsonProperty("resultCode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ResultCode { get; set; }

        /// <summary>
        /// string needed to set up a Google or Apple Pay button.
        /// </summary>
        [JsonProperty("merchantID", NullValueHandling = NullValueHandling.Ignore)]
        public string MerchantID { get; set; }

        /// <summary>
        /// Boolean indicating if Apple Pay is enabled for this merchant.
        /// </summary>
        [JsonProperty("applePay", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ApplePay { get; set; }

        /// <summary>
        /// Boolean indicating if Google Pay is enabled for this merchant.
        /// </summary>
        [JsonProperty("googlePay", NullValueHandling = NullValueHandling.Ignore)]
        public bool? GooglePay { get; set; }

        /// <summary>
        /// Array of the domains registered with apple for this domain.  For Apple Pay, each domain name a merchant uses used has to be registered with Apple before it can be used.  When calling Merchant Details the gateway first checks if the domain provided is already registered for that merchant. If it is, it will return applePay: true and resultCode: 0 and the domain will be listed in appleDomains array.  It will also list all verified domains for that merchant.  If the domain is not verified it will try to verify it and if successful will return applePay: true and the domain will be listed in applePayDomains.  If the domain is not verified successfully the response will return applePay: false and resultCode: 1. Merchant will not be able to process payment in that domain.  Apple verifies the domain by pulling down a verification text file that should be placed on http://domainname.well-known/apple-developer-merchantid-domain-association.  File name must be apple-developer-merchantid-domain-association without a file extension. The contents of the file may be served programmatically. The contents of this file will be the same for all merchants processing Apple Pay.
        /// </summary>
        [JsonProperty("applePayDomains", NullValueHandling = NullValueHandling.Ignore)]
        public object ApplePayDomains { get; set; }

        /// <summary>
        /// Message with information about the results.
        /// </summary>
        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public string Message { get; set; }

        /// <summary>
        /// String needed in the Google Pay request.
        /// </summary>
        [JsonProperty("googleJWT", NullValueHandling = NullValueHandling.Ignore)]
        public string GoogleJWT { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Data38 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Data38 other &&
                (this.ResultCode == null && other.ResultCode == null ||
                 this.ResultCode?.Equals(other.ResultCode) == true) &&
                (this.MerchantID == null && other.MerchantID == null ||
                 this.MerchantID?.Equals(other.MerchantID) == true) &&
                (this.ApplePay == null && other.ApplePay == null ||
                 this.ApplePay?.Equals(other.ApplePay) == true) &&
                (this.GooglePay == null && other.GooglePay == null ||
                 this.GooglePay?.Equals(other.GooglePay) == true) &&
                (this.ApplePayDomains == null && other.ApplePayDomains == null ||
                 this.ApplePayDomains?.Equals(other.ApplePayDomains) == true) &&
                (this.Message == null && other.Message == null ||
                 this.Message?.Equals(other.Message) == true) &&
                (this.GoogleJWT == null && other.GoogleJWT == null ||
                 this.GoogleJWT?.Equals(other.GoogleJWT) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ResultCode = {(this.ResultCode == null ? "null" : this.ResultCode.ToString())}");
            toStringOutput.Add($"MerchantID = {this.MerchantID ?? "null"}");
            toStringOutput.Add($"ApplePay = {(this.ApplePay == null ? "null" : this.ApplePay.ToString())}");
            toStringOutput.Add($"GooglePay = {(this.GooglePay == null ? "null" : this.GooglePay.ToString())}");
            toStringOutput.Add($"ApplePayDomains = {(this.ApplePayDomains == null ? "null" : this.ApplePayDomains.ToString())}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");
            toStringOutput.Add($"GoogleJWT = {this.GoogleJWT ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}