// <copyright file="Data19.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Data19.
    /// </summary>
    public class Data19
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string emailLogId;
        private string smsLogId;
        private string email;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "email_log_id", false },
            { "sms_log_id", false },
            { "email", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Data19"/> class.
        /// </summary>
        public Data19()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Data19"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="emailLogId">email_log_id.</param>
        /// <param name="smsLogId">sms_log_id.</param>
        /// <param name="success">success.</param>
        /// <param name="smsSuccess">sms_success.</param>
        /// <param name="email">email.</param>
        public Data19(
            string id = null,
            string emailLogId = null,
            string smsLogId = null,
            bool? success = null,
            bool? smsSuccess = null,
            string email = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;

            if (emailLogId != null)
            {
                this.EmailLogId = emailLogId;
            }

            if (smsLogId != null)
            {
                this.SmsLogId = smsLogId;
            }
            this.Success = success;
            this.SmsSuccess = smsSuccess;

            if (email != null)
            {
                this.Email = email;
            }
        }

        /// <summary>
        /// Quick Invoice ID
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Email Log Id
        /// </summary>
        [JsonProperty("email_log_id")]
        public string EmailLogId
        {
            get
            {
                return this.emailLogId;
            }

            set
            {
                this.shouldSerialize["email_log_id"] = true;
                this.emailLogId = value;
            }
        }

        /// <summary>
        /// SMS Log Id
        /// </summary>
        [JsonProperty("sms_log_id")]
        public string SmsLogId
        {
            get
            {
                return this.smsLogId;
            }

            set
            {
                this.shouldSerialize["sms_log_id"] = true;
                this.smsLogId = value;
            }
        }

        /// <summary>
        /// Success
        /// </summary>
        [JsonProperty("success", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Success { get; set; }

        /// <summary>
        /// SMS Success
        /// </summary>
        [JsonProperty("sms_success", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SmsSuccess { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [JsonProperty("email")]
        public string Email
        {
            get
            {
                return this.email;
            }

            set
            {
                this.shouldSerialize["email"] = true;
                this.email = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Data19 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEmailLogId()
        {
            this.shouldSerialize["email_log_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSmsLogId()
        {
            this.shouldSerialize["sms_log_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEmail()
        {
            this.shouldSerialize["email"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEmailLogId()
        {
            return this.shouldSerialize["email_log_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSmsLogId()
        {
            return this.shouldSerialize["sms_log_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEmail()
        {
            return this.shouldSerialize["email"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Data19 other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.EmailLogId == null && other.EmailLogId == null ||
                 this.EmailLogId?.Equals(other.EmailLogId) == true) &&
                (this.SmsLogId == null && other.SmsLogId == null ||
                 this.SmsLogId?.Equals(other.SmsLogId) == true) &&
                (this.Success == null && other.Success == null ||
                 this.Success?.Equals(other.Success) == true) &&
                (this.SmsSuccess == null && other.SmsSuccess == null ||
                 this.SmsSuccess?.Equals(other.SmsSuccess) == true) &&
                (this.Email == null && other.Email == null ||
                 this.Email?.Equals(other.Email) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"EmailLogId = {this.EmailLogId ?? "null"}");
            toStringOutput.Add($"SmsLogId = {this.SmsLogId ?? "null"}");
            toStringOutput.Add($"Success = {(this.Success == null ? "null" : this.Success.ToString())}");
            toStringOutput.Add($"SmsSuccess = {(this.SmsSuccess == null ? "null" : this.SmsSuccess.ToString())}");
            toStringOutput.Add($"Email = {this.Email ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}