// <copyright file="Expand40.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Expand40.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Expand40
    {
        /// <summary>
        /// Location.
        /// </summary>
        [EnumMember(Value = "location")]
        Location,

        /// <summary>
        /// CreatedUser.
        /// </summary>
        [EnumMember(Value = "created_user")]
        CreatedUser,

        /// <summary>
        /// TerminalApplication.
        /// </summary>
        [EnumMember(Value = "terminal_application")]
        TerminalApplication,

        /// <summary>
        /// Changelogs.
        /// </summary>
        [EnumMember(Value = "changelogs")]
        Changelogs,

        /// <summary>
        /// TerminalRouters.
        /// </summary>
        [EnumMember(Value = "terminal_routers")]
        TerminalRouters,

        /// <summary>
        /// HasTerminalRouters.
        /// </summary>
        [EnumMember(Value = "has_terminal_routers")]
        HasTerminalRouters,

        /// <summary>
        /// TerminalCvm.
        /// </summary>
        [EnumMember(Value = "terminal_cvm")]
        TerminalCvm,

        /// <summary>
        /// TerminalManufacturer.
        /// </summary>
        [EnumMember(Value = "terminal_manufacturer")]
        TerminalManufacturer,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}