// <copyright file="Expand47Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Expand47Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Expand47Enum
    {
        /// <summary>
        /// Location.
        /// </summary>
        [EnumMember(Value = "location")]
        Location,

        /// <summary>
        /// Contact.
        /// </summary>
        [EnumMember(Value = "contact")]
        Contact,

        /// <summary>
        /// Transactions.
        /// </summary>
        [EnumMember(Value = "transactions")]
        Transactions,

        /// <summary>
        /// ActiveRecurrings.
        /// </summary>
        [EnumMember(Value = "activeRecurrings")]
        ActiveRecurrings,

        /// <summary>
        /// IsDeletable.
        /// </summary>
        [EnumMember(Value = "is_deletable")]
        IsDeletable,

        /// <summary>
        /// Signature.
        /// </summary>
        [EnumMember(Value = "signature")]
        Signature,

        /// <summary>
        /// CreatedUser.
        /// </summary>
        [EnumMember(Value = "created_user")]
        CreatedUser,

        /// <summary>
        /// Changelogs.
        /// </summary>
        [EnumMember(Value = "changelogs")]
        Changelogs,

        /// <summary>
        /// AccountVaultCauLogs.
        /// </summary>
        [EnumMember(Value = "account_vault_cau_logs")]
        AccountVaultCauLogs,

        /// <summary>
        /// AccountVaultCauProductTransactions.
        /// </summary>
        [EnumMember(Value = "account_vault_cau_product_transactions")]
        AccountVaultCauProductTransactions
    }
}