// <copyright file="Expand5Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Expand5Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Expand5Enum
    {
        /// <summary>
        /// Recurring.
        /// </summary>
        [EnumMember(Value = "recurring")]
        Recurring,

        /// <summary>
        /// PaymentTransaction.
        /// </summary>
        [EnumMember(Value = "payment_transaction")]
        PaymentTransaction,

        /// <summary>
        /// DeclinedTransaction.
        /// </summary>
        [EnumMember(Value = "declined_transaction")]
        DeclinedTransaction
    }
}