// <copyright file="Field55Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Field55Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Field55Enum
    {
        /// <summary>
        /// RejectedTransactionId.
        /// </summary>
        [EnumMember(Value = "rejected_transaction_id")]
        RejectedTransactionId,

        /// <summary>
        /// ReturnFee.
        /// </summary>
        [EnumMember(Value = "return_fee")]
        ReturnFee,

        /// <summary>
        /// Id.
        /// </summary>
        [EnumMember(Value = "id")]
        Id,

        /// <summary>
        /// RetryTransactionId.
        /// </summary>
        [EnumMember(Value = "retry_transaction_id")]
        RetryTransactionId,

        /// <summary>
        /// ReturnFeeTransactionId.
        /// </summary>
        [EnumMember(Value = "return_fee_transaction_id")]
        ReturnFeeTransactionId,

        /// <summary>
        /// CreatedTs.
        /// </summary>
        [EnumMember(Value = "created_ts")]
        CreatedTs,

        /// <summary>
        /// CreatedUserId.
        /// </summary>
        [EnumMember(Value = "created_user_id")]
        CreatedUserId,

        /// <summary>
        /// RejectedTransaction.
        /// </summary>
        [EnumMember(Value = "rejected_transaction")]
        RejectedTransaction,

        /// <summary>
        /// RetryTransaction.
        /// </summary>
        [EnumMember(Value = "retry_transaction")]
        RetryTransaction,

        /// <summary>
        /// ReturnFeeTransaction.
        /// </summary>
        [EnumMember(Value = "return_fee_transaction")]
        ReturnFeeTransaction,

        /// <summary>
        /// CreatedUser.
        /// </summary>
        [EnumMember(Value = "created_user")]
        CreatedUser,

        /// <summary>
        /// Changelogs.
        /// </summary>
        [EnumMember(Value = "changelogs")]
        Changelogs
    }
}