// <copyright file="Field18.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Field18.
    /// </summary>
    public class Field18 : BaseModel
    {
        private string mValue;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "value", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Field18"/> class.
        /// </summary>
        public Field18()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Field18"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="label">label.</param>
        /// <param name="fieldType">field_type.</param>
        /// <param name="position">position.</param>
        /// <param name="required">required.</param>
        /// <param name="mReadonly">readonly.</param>
        /// <param name="visible">visible.</param>
        /// <param name="mValue">value.</param>
        public Field18(
            string id = null,
            string label = null,
            string fieldType = null,
            List<string> position = null,
            bool? required = null,
            bool? mReadonly = null,
            bool? visible = null,
            string mValue = null)
        {
            this.Id = id;
            this.Label = label;
            this.FieldType = fieldType;
            this.Position = position;
            this.Required = required;
            this.MReadonly = mReadonly;
            this.Visible = visible;

            if (mValue != null)
            {
                this.MValue = mValue;
            }
        }

        /// <summary>
        /// id
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Label
        /// </summary>
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        /// <summary>
        /// Field Type
        /// </summary>
        [JsonProperty("field_type", NullValueHandling = NullValueHandling.Ignore)]
        public string FieldType { get; set; }

        /// <summary>
        /// Position
        /// </summary>
        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Position { get; set; }

        /// <summary>
        /// Required
        /// </summary>
        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Required { get; set; }

        /// <summary>
        /// Read Only
        /// </summary>
        [JsonProperty("readonly", NullValueHandling = NullValueHandling.Ignore)]
        public bool? MReadonly { get; set; }

        /// <summary>
        /// Visible
        /// </summary>
        [JsonProperty("visible", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Visible { get; set; }

        /// <summary>
        /// Value
        /// </summary>
        [JsonProperty("value")]
        public string MValue
        {
            get
            {
                return this.mValue;
            }

            set
            {
                this.shouldSerialize["value"] = true;
                this.mValue = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Field18 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMValue()
        {
            this.shouldSerialize["value"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMValue()
        {
            return this.shouldSerialize["value"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Field18 other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Label == null && other.Label == null ||
                 this.Label?.Equals(other.Label) == true) &&
                (this.FieldType == null && other.FieldType == null ||
                 this.FieldType?.Equals(other.FieldType) == true) &&
                (this.Position == null && other.Position == null ||
                 this.Position?.Equals(other.Position) == true) &&
                (this.Required == null && other.Required == null ||
                 this.Required?.Equals(other.Required) == true) &&
                (this.MReadonly == null && other.MReadonly == null ||
                 this.MReadonly?.Equals(other.MReadonly) == true) &&
                (this.Visible == null && other.Visible == null ||
                 this.Visible?.Equals(other.Visible) == true) &&
                (this.MValue == null && other.MValue == null ||
                 this.MValue?.Equals(other.MValue) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Label = {this.Label ?? "null"}");
            toStringOutput.Add($"FieldType = {this.FieldType ?? "null"}");
            toStringOutput.Add($"Position = {(this.Position == null ? "null" : $"[{string.Join(", ", this.Position)} ]")}");
            toStringOutput.Add($"Required = {(this.Required == null ? "null" : this.Required.ToString())}");
            toStringOutput.Add($"MReadonly = {(this.MReadonly == null ? "null" : this.MReadonly.ToString())}");
            toStringOutput.Add($"Visible = {(this.Visible == null ? "null" : this.Visible.ToString())}");
            toStringOutput.Add($"MValue = {this.MValue ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}