// <copyright file="IdtypeEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// IdtypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum IdtypeEnum
    {
        /// <summary>
        /// Mac.
        /// </summary>
        [EnumMember(Value = "mac")]
        Mac,

        /// <summary>
        /// Sn.
        /// </summary>
        [EnumMember(Value = "sn")]
        Sn
    }
}