// <copyright file="IntervalTypeEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// IntervalTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum IntervalTypeEnum
    {
        /// <summary>
        /// D.
        /// </summary>
        [EnumMember(Value = "d")]
        D,

        /// <summary>
        /// W.
        /// </summary>
        [EnumMember(Value = "w")]
        W,

        /// <summary>
        /// M.
        /// </summary>
        [EnumMember(Value = "m")]
        M
    }
}