// <copyright file="Joi4.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisAPI.Standard.Models.Containers;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Joi4.
    /// </summary>
    public class Joi4 : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Joi4"/> class.
        /// </summary>
        public Joi4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Joi4"/> class.
        /// </summary>
        /// <param name="conditions">conditions.</param>
        public Joi4(
            Joi4Conditions conditions = null)
        {
            this.Conditions = conditions;
        }

        /// <summary>
        /// Gets or sets Conditions.
        /// </summary>
        [JsonProperty("conditions", NullValueHandling = NullValueHandling.Ignore)]
        public Joi4Conditions Conditions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Joi4 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Joi4 other &&
                (this.Conditions == null && other.Conditions == null ||
                 this.Conditions?.Equals(other.Conditions) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Conditions = {(this.Conditions == null ? "null" : this.Conditions.ToString())}");

            base.ToString(toStringOutput);
        }
    }
}