// <copyright file="List8.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// List8.
    /// </summary>
    public class List8 : BaseModel
    {
        private string id;
        private string companyId;
        private string service;
        private string traceNumber;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "id", false },
            { "company_id", false },
            { "service", false },
            { "trace_number", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="List8"/> class.
        /// </summary>
        public List8()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="List8"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="companyId">company_id.</param>
        /// <param name="merchantId">merchant_id.</param>
        /// <param name="service">service.</param>
        /// <param name="depositTypes">deposit_types.</param>
        /// <param name="depositAmount">deposit_amount.</param>
        /// <param name="batchAmount">batch_amount.</param>
        /// <param name="adjustmentAmount">adjustment_amount.</param>
        /// <param name="retainedAmount">retained_amount.</param>
        /// <param name="conveyedAmount">conveyed_amount.</param>
        /// <param name="feeAmount">fee_amount.</param>
        /// <param name="referenceNumber">reference_number.</param>
        /// <param name="traceNumber">trace_number.</param>
        /// <param name="currency">currency.</param>
        /// <param name="createdTs">created_ts.</param>
        /// <param name="reportedDate">reported_date.</param>
        /// <param name="transactionDate">transaction_date.</param>
        /// <param name="depositAccount">deposit_account.</param>
        /// <param name="details">details.</param>
        public List8(
            string id = null,
            string companyId = null,
            string merchantId = null,
            string service = null,
            List<Models.DepositTypeEnum> depositTypes = null,
            double? depositAmount = null,
            double? batchAmount = null,
            double? adjustmentAmount = null,
            double? retainedAmount = null,
            double? conveyedAmount = null,
            double? feeAmount = null,
            string referenceNumber = null,
            string traceNumber = null,
            string currency = null,
            int? createdTs = null,
            string reportedDate = null,
            string transactionDate = null,
            string depositAccount = null,
            List<Models.Detail2> details = null)
        {

            if (id != null)
            {
                this.Id = id;
            }

            if (companyId != null)
            {
                this.CompanyId = companyId;
            }
            this.MerchantId = merchantId;

            if (service != null)
            {
                this.Service = service;
            }
            this.DepositTypes = depositTypes;
            this.DepositAmount = depositAmount;
            this.BatchAmount = batchAmount;
            this.AdjustmentAmount = adjustmentAmount;
            this.RetainedAmount = retainedAmount;
            this.ConveyedAmount = conveyedAmount;
            this.FeeAmount = feeAmount;
            this.ReferenceNumber = referenceNumber;

            if (traceNumber != null)
            {
                this.TraceNumber = traceNumber;
            }
            this.Currency = currency;
            this.CreatedTs = createdTs;
            this.ReportedDate = reportedDate;
            this.TransactionDate = transactionDate;
            this.DepositAccount = depositAccount;
            this.Details = details;
        }

        /// <summary>
        /// Deposit Id
        /// </summary>
        [JsonProperty("id")]
        public string Id
        {
            get
            {
                return this.id;
            }

            set
            {
                this.shouldSerialize["id"] = true;
                this.id = value;
            }
        }

        /// <summary>
        /// Company Id
        /// </summary>
        [JsonProperty("company_id")]
        public string CompanyId
        {
            get
            {
                return this.companyId;
            }

            set
            {
                this.shouldSerialize["company_id"] = true;
                this.companyId = value;
            }
        }

        /// <summary>
        /// Merchant Id
        /// </summary>
        [JsonProperty("merchant_id", NullValueHandling = NullValueHandling.Ignore)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Service
        /// </summary>
        [JsonProperty("service")]
        public string Service
        {
            get
            {
                return this.service;
            }

            set
            {
                this.shouldSerialize["service"] = true;
                this.service = value;
            }
        }

        /// <summary>
        /// Gets or sets DepositTypes.
        /// </summary>
        [JsonProperty("deposit_types", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.DepositTypeEnum> DepositTypes { get; set; }

        /// <summary>
        /// Deposit Amount
        /// </summary>
        [JsonProperty("deposit_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? DepositAmount { get; set; }

        /// <summary>
        /// Batch Amount
        /// </summary>
        [JsonProperty("batch_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? BatchAmount { get; set; }

        /// <summary>
        /// Adjustment Amount
        /// </summary>
        [JsonProperty("adjustment_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? AdjustmentAmount { get; set; }

        /// <summary>
        /// Retained Amount
        /// </summary>
        [JsonProperty("retained_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? RetainedAmount { get; set; }

        /// <summary>
        /// Conveyed Amount
        /// </summary>
        [JsonProperty("conveyed_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? ConveyedAmount { get; set; }

        /// <summary>
        /// Fee Amount
        /// </summary>
        [JsonProperty("fee_amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? FeeAmount { get; set; }

        /// <summary>
        /// Reference Number
        /// </summary>
        [JsonProperty("reference_number", NullValueHandling = NullValueHandling.Ignore)]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or sets TraceNumber.
        /// </summary>
        [JsonProperty("trace_number")]
        public string TraceNumber
        {
            get
            {
                return this.traceNumber;
            }

            set
            {
                this.shouldSerialize["trace_number"] = true;
                this.traceNumber = value;
            }
        }

        /// <summary>
        /// Currency
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Created Timestamp
        /// </summary>
        [JsonProperty("created_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? CreatedTs { get; set; }

        /// <summary>
        /// Reported Date
        /// </summary>
        [JsonProperty("reported_date", NullValueHandling = NullValueHandling.Ignore)]
        public string ReportedDate { get; set; }

        /// <summary>
        /// Transaction Date
        /// </summary>
        [JsonProperty("transaction_date", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionDate { get; set; }

        /// <summary>
        /// Deposit Account
        /// </summary>
        [JsonProperty("deposit_account", NullValueHandling = NullValueHandling.Ignore)]
        public string DepositAccount { get; set; }

        /// <summary>
        /// Gets or sets Details.
        /// </summary>
        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Detail2> Details { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"List8 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetId()
        {
            this.shouldSerialize["id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCompanyId()
        {
            this.shouldSerialize["company_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetService()
        {
            this.shouldSerialize["service"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTraceNumber()
        {
            this.shouldSerialize["trace_number"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeId()
        {
            return this.shouldSerialize["id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCompanyId()
        {
            return this.shouldSerialize["company_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeService()
        {
            return this.shouldSerialize["service"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTraceNumber()
        {
            return this.shouldSerialize["trace_number"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is List8 other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.CompanyId == null && other.CompanyId == null ||
                 this.CompanyId?.Equals(other.CompanyId) == true) &&
                (this.MerchantId == null && other.MerchantId == null ||
                 this.MerchantId?.Equals(other.MerchantId) == true) &&
                (this.Service == null && other.Service == null ||
                 this.Service?.Equals(other.Service) == true) &&
                (this.DepositTypes == null && other.DepositTypes == null ||
                 this.DepositTypes?.Equals(other.DepositTypes) == true) &&
                (this.DepositAmount == null && other.DepositAmount == null ||
                 this.DepositAmount?.Equals(other.DepositAmount) == true) &&
                (this.BatchAmount == null && other.BatchAmount == null ||
                 this.BatchAmount?.Equals(other.BatchAmount) == true) &&
                (this.AdjustmentAmount == null && other.AdjustmentAmount == null ||
                 this.AdjustmentAmount?.Equals(other.AdjustmentAmount) == true) &&
                (this.RetainedAmount == null && other.RetainedAmount == null ||
                 this.RetainedAmount?.Equals(other.RetainedAmount) == true) &&
                (this.ConveyedAmount == null && other.ConveyedAmount == null ||
                 this.ConveyedAmount?.Equals(other.ConveyedAmount) == true) &&
                (this.FeeAmount == null && other.FeeAmount == null ||
                 this.FeeAmount?.Equals(other.FeeAmount) == true) &&
                (this.ReferenceNumber == null && other.ReferenceNumber == null ||
                 this.ReferenceNumber?.Equals(other.ReferenceNumber) == true) &&
                (this.TraceNumber == null && other.TraceNumber == null ||
                 this.TraceNumber?.Equals(other.TraceNumber) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                (this.ReportedDate == null && other.ReportedDate == null ||
                 this.ReportedDate?.Equals(other.ReportedDate) == true) &&
                (this.TransactionDate == null && other.TransactionDate == null ||
                 this.TransactionDate?.Equals(other.TransactionDate) == true) &&
                (this.DepositAccount == null && other.DepositAccount == null ||
                 this.DepositAccount?.Equals(other.DepositAccount) == true) &&
                (this.Details == null && other.Details == null ||
                 this.Details?.Equals(other.Details) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"CompanyId = {this.CompanyId ?? "null"}");
            toStringOutput.Add($"MerchantId = {this.MerchantId ?? "null"}");
            toStringOutput.Add($"Service = {this.Service ?? "null"}");
            toStringOutput.Add($"DepositTypes = {(this.DepositTypes == null ? "null" : $"[{string.Join(", ", this.DepositTypes)} ]")}");
            toStringOutput.Add($"DepositAmount = {(this.DepositAmount == null ? "null" : this.DepositAmount.ToString())}");
            toStringOutput.Add($"BatchAmount = {(this.BatchAmount == null ? "null" : this.BatchAmount.ToString())}");
            toStringOutput.Add($"AdjustmentAmount = {(this.AdjustmentAmount == null ? "null" : this.AdjustmentAmount.ToString())}");
            toStringOutput.Add($"RetainedAmount = {(this.RetainedAmount == null ? "null" : this.RetainedAmount.ToString())}");
            toStringOutput.Add($"ConveyedAmount = {(this.ConveyedAmount == null ? "null" : this.ConveyedAmount.ToString())}");
            toStringOutput.Add($"FeeAmount = {(this.FeeAmount == null ? "null" : this.FeeAmount.ToString())}");
            toStringOutput.Add($"ReferenceNumber = {this.ReferenceNumber ?? "null"}");
            toStringOutput.Add($"TraceNumber = {this.TraceNumber ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");
            toStringOutput.Add($"ReportedDate = {this.ReportedDate ?? "null"}");
            toStringOutput.Add($"TransactionDate = {this.TransactionDate ?? "null"}");
            toStringOutput.Add($"DepositAccount = {this.DepositAccount ?? "null"}");
            toStringOutput.Add($"Details = {(this.Details == null ? "null" : $"[{string.Join(", ", this.Details)} ]")}");

            base.ToString(toStringOutput);
        }
    }
}