// <copyright file="LogSms.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// LogSms.
    /// </summary>
    public class LogSms : BaseModel
    {
        private string body;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "body", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="LogSms"/> class.
        /// </summary>
        public LogSms()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LogSms"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="body">body.</param>
        /// <param name="reasonModel">reason_model.</param>
        /// <param name="reasonModelId">reason_model_id.</param>
        /// <param name="providerId">provider_id.</param>
        /// <param name="status">status.</param>
        /// <param name="sender">sender.</param>
        /// <param name="recipient">recipient.</param>
        /// <param name="createdTs">created_ts.</param>
        /// <param name="createdUserId">created_user_id.</param>
        public LogSms(
            string id = null,
            string body = null,
            string reasonModel = null,
            string reasonModelId = null,
            string providerId = null,
            string status = null,
            string sender = null,
            string recipient = null,
            int? createdTs = null,
            string createdUserId = null)
        {
            this.Id = id;

            if (body != null)
            {
                this.Body = body;
            }
            this.ReasonModel = reasonModel;
            this.ReasonModelId = reasonModelId;
            this.ProviderId = providerId;
            this.Status = status;
            this.Sender = sender;
            this.Recipient = recipient;
            this.CreatedTs = createdTs;
            this.CreatedUserId = createdUserId;
        }

        /// <summary>
        /// Log Sms Id
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Body
        /// </summary>
        [JsonProperty("body")]
        public string Body
        {
            get
            {
                return this.body;
            }

            set
            {
                this.shouldSerialize["body"] = true;
                this.body = value;
            }
        }

        /// <summary>
        /// Reason Model
        /// </summary>
        [JsonProperty("reason_model", NullValueHandling = NullValueHandling.Ignore)]
        public string ReasonModel { get; set; }

        /// <summary>
        /// Reason Model ID
        /// </summary>
        [JsonProperty("reason_model_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ReasonModelId { get; set; }

        /// <summary>
        /// Provider ID
        /// </summary>
        [JsonProperty("provider_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ProviderId { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Sender
        /// </summary>
        [JsonProperty("sender", NullValueHandling = NullValueHandling.Ignore)]
        public string Sender { get; set; }

        /// <summary>
        /// Recipient
        /// </summary>
        [JsonProperty("recipient", NullValueHandling = NullValueHandling.Ignore)]
        public string Recipient { get; set; }

        /// <summary>
        /// Created Time Stamp
        /// </summary>
        [JsonProperty("created_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? CreatedTs { get; set; }

        /// <summary>
        /// User ID Created the register
        /// </summary>
        [JsonProperty("created_user_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedUserId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LogSms : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetBody()
        {
            this.shouldSerialize["body"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeBody()
        {
            return this.shouldSerialize["body"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LogSms other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Body == null && other.Body == null ||
                 this.Body?.Equals(other.Body) == true) &&
                (this.ReasonModel == null && other.ReasonModel == null ||
                 this.ReasonModel?.Equals(other.ReasonModel) == true) &&
                (this.ReasonModelId == null && other.ReasonModelId == null ||
                 this.ReasonModelId?.Equals(other.ReasonModelId) == true) &&
                (this.ProviderId == null && other.ProviderId == null ||
                 this.ProviderId?.Equals(other.ProviderId) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Sender == null && other.Sender == null ||
                 this.Sender?.Equals(other.Sender) == true) &&
                (this.Recipient == null && other.Recipient == null ||
                 this.Recipient?.Equals(other.Recipient) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                (this.CreatedUserId == null && other.CreatedUserId == null ||
                 this.CreatedUserId?.Equals(other.CreatedUserId) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Body = {this.Body ?? "null"}");
            toStringOutput.Add($"ReasonModel = {this.ReasonModel ?? "null"}");
            toStringOutput.Add($"ReasonModelId = {this.ReasonModelId ?? "null"}");
            toStringOutput.Add($"ProviderId = {this.ProviderId ?? "null"}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"Sender = {this.Sender ?? "null"}");
            toStringOutput.Add($"Recipient = {this.Recipient ?? "null"}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");
            toStringOutput.Add($"CreatedUserId = {this.CreatedUserId ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}