// <copyright file="PreferredLanguage.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// PreferredLanguage.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum PreferredLanguage
    {
        /// <summary>
        /// EnUs.
        /// </summary>
        [EnumMember(Value = "en-US")]
        EnUs,

        /// <summary>
        /// FrCa.
        /// </summary>
        [EnumMember(Value = "fr-CA")]
        FrCa,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}