// <copyright file="ProcessMethodEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ProcessMethodEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProcessMethodEnum
    {
        /// <summary>
        /// VirtualTerminal.
        /// </summary>
        [EnumMember(Value = "virtual_terminal")]
        VirtualTerminal,

        /// <summary>
        /// PhysicalTerminal.
        /// </summary>
        [EnumMember(Value = "physical_terminal")]
        PhysicalTerminal
    }
}