// <copyright file="Processor.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Processor.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Processor
    {
        /// <summary>
        /// Zgate.
        /// </summary>
        [EnumMember(Value = "zgate")]
        Zgate,

        /// <summary>
        /// Zgate2.
        /// </summary>
        [EnumMember(Value = "zgate2")]
        Zgate2,

        /// <summary>
        /// Zach.
        /// </summary>
        [EnumMember(Value = "zach")]
        Zach,

        /// <summary>
        /// Ach.
        /// </summary>
        [EnumMember(Value = "ach")]
        Ach,

        /// <summary>
        /// Fortisach.
        /// </summary>
        [EnumMember(Value = "fortisach")]
        Fortisach,

        /// <summary>
        /// Cash.
        /// </summary>
        [EnumMember(Value = "cash")]
        Cash,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}