// <copyright file="ProductInvoice.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// ProductInvoice.
    /// </summary>
    public class ProductInvoice
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string quoteNumberFormat;
        private double? quoteNumberStart;
        private double? quoteNumberIncrement;
        private double? quoteNumberCurrent;
        private string invoiceNumberFormat;
        private double? invoiceNumberStart;
        private double? invoiceNumberIncrement;
        private double? invoiceNumberCurrent;
        private int? taxFee;
        private int? monthlyFee;
        private double? selectable;
        private double? reportable;
        private string portfolioId;
        private string createdUserId;
        private string modifiedUserId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "quote_number_format", false },
            { "quote_number_start", false },
            { "quote_number_increment", false },
            { "quote_number_current", false },
            { "invoice_number_format", false },
            { "invoice_number_start", false },
            { "invoice_number_increment", false },
            { "invoice_number_current", false },
            { "tax_fee", false },
            { "monthly_fee", false },
            { "selectable", false },
            { "reportable", false },
            { "portfolio_id", false },
            { "created_user_id", false },
            { "modified_user_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductInvoice"/> class.
        /// </summary>
        public ProductInvoice()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductInvoice"/> class.
        /// </summary>
        /// <param name="title">title.</param>
        /// <param name="quoteNumberFormat">quote_number_format.</param>
        /// <param name="quoteNumberStart">quote_number_start.</param>
        /// <param name="quoteNumberIncrement">quote_number_increment.</param>
        /// <param name="quoteNumberCurrent">quote_number_current.</param>
        /// <param name="invoiceNumberFormat">invoice_number_format.</param>
        /// <param name="invoiceNumberStart">invoice_number_start.</param>
        /// <param name="invoiceNumberIncrement">invoice_number_increment.</param>
        /// <param name="invoiceNumberCurrent">invoice_number_current.</param>
        /// <param name="taxRate">tax_rate.</param>
        /// <param name="taxFee">tax_fee.</param>
        /// <param name="monthlyFee">monthly_fee.</param>
        /// <param name="perInvoiceFee">per_invoice_fee.</param>
        /// <param name="perQuoteFee">per_quote_fee.</param>
        /// <param name="requirePayInFull">require_pay_in_full.</param>
        /// <param name="selectable">selectable.</param>
        /// <param name="reportable">reportable.</param>
        /// <param name="portfolioId">portfolio_id.</param>
        /// <param name="locationId">location_id.</param>
        /// <param name="id">id.</param>
        /// <param name="createdTs">created_ts.</param>
        /// <param name="modifiedTs">modified_ts.</param>
        /// <param name="createdUserId">created_user_id.</param>
        /// <param name="modifiedUserId">modified_user_id.</param>
        public ProductInvoice(
            string title = null,
            string quoteNumberFormat = null,
            double? quoteNumberStart = null,
            double? quoteNumberIncrement = null,
            double? quoteNumberCurrent = null,
            string invoiceNumberFormat = null,
            double? invoiceNumberStart = null,
            double? invoiceNumberIncrement = null,
            double? invoiceNumberCurrent = null,
            double? taxRate = null,
            int? taxFee = null,
            int? monthlyFee = null,
            int? perInvoiceFee = null,
            int? perQuoteFee = null,
            bool? requirePayInFull = null,
            double? selectable = null,
            double? reportable = null,
            string portfolioId = null,
            string locationId = null,
            string id = null,
            int? createdTs = null,
            int? modifiedTs = null,
            string createdUserId = null,
            string modifiedUserId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Title = title;

            if (quoteNumberFormat != null)
            {
                this.QuoteNumberFormat = quoteNumberFormat;
            }

            if (quoteNumberStart != null)
            {
                this.QuoteNumberStart = quoteNumberStart;
            }

            if (quoteNumberIncrement != null)
            {
                this.QuoteNumberIncrement = quoteNumberIncrement;
            }

            if (quoteNumberCurrent != null)
            {
                this.QuoteNumberCurrent = quoteNumberCurrent;
            }

            if (invoiceNumberFormat != null)
            {
                this.InvoiceNumberFormat = invoiceNumberFormat;
            }

            if (invoiceNumberStart != null)
            {
                this.InvoiceNumberStart = invoiceNumberStart;
            }

            if (invoiceNumberIncrement != null)
            {
                this.InvoiceNumberIncrement = invoiceNumberIncrement;
            }

            if (invoiceNumberCurrent != null)
            {
                this.InvoiceNumberCurrent = invoiceNumberCurrent;
            }
            this.TaxRate = taxRate;

            if (taxFee != null)
            {
                this.TaxFee = taxFee;
            }

            if (monthlyFee != null)
            {
                this.MonthlyFee = monthlyFee;
            }
            this.PerInvoiceFee = perInvoiceFee;
            this.PerQuoteFee = perQuoteFee;
            this.RequirePayInFull = requirePayInFull;

            if (selectable != null)
            {
                this.Selectable = selectable;
            }

            if (reportable != null)
            {
                this.Reportable = reportable;
            }

            if (portfolioId != null)
            {
                this.PortfolioId = portfolioId;
            }
            this.LocationId = locationId;
            this.Id = id;
            this.CreatedTs = createdTs;
            this.ModifiedTs = modifiedTs;

            if (createdUserId != null)
            {
                this.CreatedUserId = createdUserId;
            }

            if (modifiedUserId != null)
            {
                this.ModifiedUserId = modifiedUserId;
            }
        }

        /// <summary>
        /// Title
        /// </summary>
        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }

        /// <summary>
        /// Quote Number Format
        /// </summary>
        [JsonProperty("quote_number_format")]
        public string QuoteNumberFormat
        {
            get
            {
                return this.quoteNumberFormat;
            }

            set
            {
                this.shouldSerialize["quote_number_format"] = true;
                this.quoteNumberFormat = value;
            }
        }

        /// <summary>
        /// Quote Number Start
        /// </summary>
        [JsonProperty("quote_number_start")]
        public double? QuoteNumberStart
        {
            get
            {
                return this.quoteNumberStart;
            }

            set
            {
                this.shouldSerialize["quote_number_start"] = true;
                this.quoteNumberStart = value;
            }
        }

        /// <summary>
        /// Quote Number Increment
        /// </summary>
        [JsonProperty("quote_number_increment")]
        public double? QuoteNumberIncrement
        {
            get
            {
                return this.quoteNumberIncrement;
            }

            set
            {
                this.shouldSerialize["quote_number_increment"] = true;
                this.quoteNumberIncrement = value;
            }
        }

        /// <summary>
        /// Quote Number Current
        /// </summary>
        [JsonProperty("quote_number_current")]
        public double? QuoteNumberCurrent
        {
            get
            {
                return this.quoteNumberCurrent;
            }

            set
            {
                this.shouldSerialize["quote_number_current"] = true;
                this.quoteNumberCurrent = value;
            }
        }

        /// <summary>
        /// Invoice Number Format
        /// </summary>
        [JsonProperty("invoice_number_format")]
        public string InvoiceNumberFormat
        {
            get
            {
                return this.invoiceNumberFormat;
            }

            set
            {
                this.shouldSerialize["invoice_number_format"] = true;
                this.invoiceNumberFormat = value;
            }
        }

        /// <summary>
        /// Invoice Number Start
        /// </summary>
        [JsonProperty("invoice_number_start")]
        public double? InvoiceNumberStart
        {
            get
            {
                return this.invoiceNumberStart;
            }

            set
            {
                this.shouldSerialize["invoice_number_start"] = true;
                this.invoiceNumberStart = value;
            }
        }

        /// <summary>
        /// Invoice Number Increment
        /// </summary>
        [JsonProperty("invoice_number_increment")]
        public double? InvoiceNumberIncrement
        {
            get
            {
                return this.invoiceNumberIncrement;
            }

            set
            {
                this.shouldSerialize["invoice_number_increment"] = true;
                this.invoiceNumberIncrement = value;
            }
        }

        /// <summary>
        /// Invoice Number Current
        /// </summary>
        [JsonProperty("invoice_number_current")]
        public double? InvoiceNumberCurrent
        {
            get
            {
                return this.invoiceNumberCurrent;
            }

            set
            {
                this.shouldSerialize["invoice_number_current"] = true;
                this.invoiceNumberCurrent = value;
            }
        }

        /// <summary>
        /// Tax Rate
        /// </summary>
        [JsonProperty("tax_rate", NullValueHandling = NullValueHandling.Ignore)]
        public double? TaxRate { get; set; }

        /// <summary>
        /// Tax Fee
        /// </summary>
        [JsonProperty("tax_fee")]
        public int? TaxFee
        {
            get
            {
                return this.taxFee;
            }

            set
            {
                this.shouldSerialize["tax_fee"] = true;
                this.taxFee = value;
            }
        }

        /// <summary>
        /// Monthly Fees
        /// </summary>
        [JsonProperty("monthly_fee")]
        public int? MonthlyFee
        {
            get
            {
                return this.monthlyFee;
            }

            set
            {
                this.shouldSerialize["monthly_fee"] = true;
                this.monthlyFee = value;
            }
        }

        /// <summary>
        /// Per Invoice Fee
        /// </summary>
        [JsonProperty("per_invoice_fee", NullValueHandling = NullValueHandling.Ignore)]
        public int? PerInvoiceFee { get; set; }

        /// <summary>
        /// Per Quote fee
        /// </summary>
        [JsonProperty("per_quote_fee", NullValueHandling = NullValueHandling.Ignore)]
        public int? PerQuoteFee { get; set; }

        /// <summary>
        /// Require Pay In Full
        /// </summary>
        [JsonProperty("require_pay_in_full", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RequirePayInFull { get; set; }

        /// <summary>
        /// Selectable
        /// </summary>
        [JsonProperty("selectable")]
        public double? Selectable
        {
            get
            {
                return this.selectable;
            }

            set
            {
                this.shouldSerialize["selectable"] = true;
                this.selectable = value;
            }
        }

        /// <summary>
        /// Reportable
        /// </summary>
        [JsonProperty("reportable")]
        public double? Reportable
        {
            get
            {
                return this.reportable;
            }

            set
            {
                this.shouldSerialize["reportable"] = true;
                this.reportable = value;
            }
        }

        /// <summary>
        /// Portfolio Id
        /// </summary>
        [JsonProperty("portfolio_id")]
        public string PortfolioId
        {
            get
            {
                return this.portfolioId;
            }

            set
            {
                this.shouldSerialize["portfolio_id"] = true;
                this.portfolioId = value;
            }
        }

        /// <summary>
        /// Location ID
        /// </summary>
        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationId { get; set; }

        /// <summary>
        /// Product Invoice Id
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Created Time Stamp
        /// </summary>
        [JsonProperty("created_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? CreatedTs { get; set; }

        /// <summary>
        /// Modified Time Stamp
        /// </summary>
        [JsonProperty("modified_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? ModifiedTs { get; set; }

        /// <summary>
        /// User ID Created the register
        /// </summary>
        [JsonProperty("created_user_id")]
        public string CreatedUserId
        {
            get
            {
                return this.createdUserId;
            }

            set
            {
                this.shouldSerialize["created_user_id"] = true;
                this.createdUserId = value;
            }
        }

        /// <summary>
        /// Last User ID that updated the register
        /// </summary>
        [JsonProperty("modified_user_id")]
        public string ModifiedUserId
        {
            get
            {
                return this.modifiedUserId;
            }

            set
            {
                this.shouldSerialize["modified_user_id"] = true;
                this.modifiedUserId = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProductInvoice : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetQuoteNumberFormat()
        {
            this.shouldSerialize["quote_number_format"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetQuoteNumberStart()
        {
            this.shouldSerialize["quote_number_start"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetQuoteNumberIncrement()
        {
            this.shouldSerialize["quote_number_increment"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetQuoteNumberCurrent()
        {
            this.shouldSerialize["quote_number_current"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetInvoiceNumberFormat()
        {
            this.shouldSerialize["invoice_number_format"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetInvoiceNumberStart()
        {
            this.shouldSerialize["invoice_number_start"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetInvoiceNumberIncrement()
        {
            this.shouldSerialize["invoice_number_increment"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetInvoiceNumberCurrent()
        {
            this.shouldSerialize["invoice_number_current"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaxFee()
        {
            this.shouldSerialize["tax_fee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMonthlyFee()
        {
            this.shouldSerialize["monthly_fee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSelectable()
        {
            this.shouldSerialize["selectable"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetReportable()
        {
            this.shouldSerialize["reportable"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPortfolioId()
        {
            this.shouldSerialize["portfolio_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCreatedUserId()
        {
            this.shouldSerialize["created_user_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetModifiedUserId()
        {
            this.shouldSerialize["modified_user_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeQuoteNumberFormat()
        {
            return this.shouldSerialize["quote_number_format"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeQuoteNumberStart()
        {
            return this.shouldSerialize["quote_number_start"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeQuoteNumberIncrement()
        {
            return this.shouldSerialize["quote_number_increment"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeQuoteNumberCurrent()
        {
            return this.shouldSerialize["quote_number_current"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeInvoiceNumberFormat()
        {
            return this.shouldSerialize["invoice_number_format"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeInvoiceNumberStart()
        {
            return this.shouldSerialize["invoice_number_start"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeInvoiceNumberIncrement()
        {
            return this.shouldSerialize["invoice_number_increment"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeInvoiceNumberCurrent()
        {
            return this.shouldSerialize["invoice_number_current"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaxFee()
        {
            return this.shouldSerialize["tax_fee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMonthlyFee()
        {
            return this.shouldSerialize["monthly_fee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSelectable()
        {
            return this.shouldSerialize["selectable"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeReportable()
        {
            return this.shouldSerialize["reportable"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePortfolioId()
        {
            return this.shouldSerialize["portfolio_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCreatedUserId()
        {
            return this.shouldSerialize["created_user_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeModifiedUserId()
        {
            return this.shouldSerialize["modified_user_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ProductInvoice other &&
                (this.Title == null && other.Title == null ||
                 this.Title?.Equals(other.Title) == true) &&
                (this.QuoteNumberFormat == null && other.QuoteNumberFormat == null ||
                 this.QuoteNumberFormat?.Equals(other.QuoteNumberFormat) == true) &&
                (this.QuoteNumberStart == null && other.QuoteNumberStart == null ||
                 this.QuoteNumberStart?.Equals(other.QuoteNumberStart) == true) &&
                (this.QuoteNumberIncrement == null && other.QuoteNumberIncrement == null ||
                 this.QuoteNumberIncrement?.Equals(other.QuoteNumberIncrement) == true) &&
                (this.QuoteNumberCurrent == null && other.QuoteNumberCurrent == null ||
                 this.QuoteNumberCurrent?.Equals(other.QuoteNumberCurrent) == true) &&
                (this.InvoiceNumberFormat == null && other.InvoiceNumberFormat == null ||
                 this.InvoiceNumberFormat?.Equals(other.InvoiceNumberFormat) == true) &&
                (this.InvoiceNumberStart == null && other.InvoiceNumberStart == null ||
                 this.InvoiceNumberStart?.Equals(other.InvoiceNumberStart) == true) &&
                (this.InvoiceNumberIncrement == null && other.InvoiceNumberIncrement == null ||
                 this.InvoiceNumberIncrement?.Equals(other.InvoiceNumberIncrement) == true) &&
                (this.InvoiceNumberCurrent == null && other.InvoiceNumberCurrent == null ||
                 this.InvoiceNumberCurrent?.Equals(other.InvoiceNumberCurrent) == true) &&
                (this.TaxRate == null && other.TaxRate == null ||
                 this.TaxRate?.Equals(other.TaxRate) == true) &&
                (this.TaxFee == null && other.TaxFee == null ||
                 this.TaxFee?.Equals(other.TaxFee) == true) &&
                (this.MonthlyFee == null && other.MonthlyFee == null ||
                 this.MonthlyFee?.Equals(other.MonthlyFee) == true) &&
                (this.PerInvoiceFee == null && other.PerInvoiceFee == null ||
                 this.PerInvoiceFee?.Equals(other.PerInvoiceFee) == true) &&
                (this.PerQuoteFee == null && other.PerQuoteFee == null ||
                 this.PerQuoteFee?.Equals(other.PerQuoteFee) == true) &&
                (this.RequirePayInFull == null && other.RequirePayInFull == null ||
                 this.RequirePayInFull?.Equals(other.RequirePayInFull) == true) &&
                (this.Selectable == null && other.Selectable == null ||
                 this.Selectable?.Equals(other.Selectable) == true) &&
                (this.Reportable == null && other.Reportable == null ||
                 this.Reportable?.Equals(other.Reportable) == true) &&
                (this.PortfolioId == null && other.PortfolioId == null ||
                 this.PortfolioId?.Equals(other.PortfolioId) == true) &&
                (this.LocationId == null && other.LocationId == null ||
                 this.LocationId?.Equals(other.LocationId) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                (this.ModifiedTs == null && other.ModifiedTs == null ||
                 this.ModifiedTs?.Equals(other.ModifiedTs) == true) &&
                (this.CreatedUserId == null && other.CreatedUserId == null ||
                 this.CreatedUserId?.Equals(other.CreatedUserId) == true) &&
                (this.ModifiedUserId == null && other.ModifiedUserId == null ||
                 this.ModifiedUserId?.Equals(other.ModifiedUserId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Title = {this.Title ?? "null"}");
            toStringOutput.Add($"QuoteNumberFormat = {this.QuoteNumberFormat ?? "null"}");
            toStringOutput.Add($"QuoteNumberStart = {(this.QuoteNumberStart == null ? "null" : this.QuoteNumberStart.ToString())}");
            toStringOutput.Add($"QuoteNumberIncrement = {(this.QuoteNumberIncrement == null ? "null" : this.QuoteNumberIncrement.ToString())}");
            toStringOutput.Add($"QuoteNumberCurrent = {(this.QuoteNumberCurrent == null ? "null" : this.QuoteNumberCurrent.ToString())}");
            toStringOutput.Add($"InvoiceNumberFormat = {this.InvoiceNumberFormat ?? "null"}");
            toStringOutput.Add($"InvoiceNumberStart = {(this.InvoiceNumberStart == null ? "null" : this.InvoiceNumberStart.ToString())}");
            toStringOutput.Add($"InvoiceNumberIncrement = {(this.InvoiceNumberIncrement == null ? "null" : this.InvoiceNumberIncrement.ToString())}");
            toStringOutput.Add($"InvoiceNumberCurrent = {(this.InvoiceNumberCurrent == null ? "null" : this.InvoiceNumberCurrent.ToString())}");
            toStringOutput.Add($"TaxRate = {(this.TaxRate == null ? "null" : this.TaxRate.ToString())}");
            toStringOutput.Add($"TaxFee = {(this.TaxFee == null ? "null" : this.TaxFee.ToString())}");
            toStringOutput.Add($"MonthlyFee = {(this.MonthlyFee == null ? "null" : this.MonthlyFee.ToString())}");
            toStringOutput.Add($"PerInvoiceFee = {(this.PerInvoiceFee == null ? "null" : this.PerInvoiceFee.ToString())}");
            toStringOutput.Add($"PerQuoteFee = {(this.PerQuoteFee == null ? "null" : this.PerQuoteFee.ToString())}");
            toStringOutput.Add($"RequirePayInFull = {(this.RequirePayInFull == null ? "null" : this.RequirePayInFull.ToString())}");
            toStringOutput.Add($"Selectable = {(this.Selectable == null ? "null" : this.Selectable.ToString())}");
            toStringOutput.Add($"Reportable = {(this.Reportable == null ? "null" : this.Reportable.ToString())}");
            toStringOutput.Add($"PortfolioId = {this.PortfolioId ?? "null"}");
            toStringOutput.Add($"LocationId = {this.LocationId ?? "null"}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");
            toStringOutput.Add($"ModifiedTs = {(this.ModifiedTs == null ? "null" : this.ModifiedTs.ToString())}");
            toStringOutput.Add($"CreatedUserId = {this.CreatedUserId ?? "null"}");
            toStringOutput.Add($"ModifiedUserId = {this.ModifiedUserId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}