// <copyright file="RegistrationField.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// RegistrationField.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum RegistrationField
    {
        /// <summary>
        /// Id.
        /// </summary>
        [EnumMember(Value = "id")]
        Id,

        /// <summary>
        /// FirstName.
        /// </summary>
        [EnumMember(Value = "first_name")]
        FirstName,

        /// <summary>
        /// LastName.
        /// </summary>
        [EnumMember(Value = "last_name")]
        LastName,

        /// <summary>
        /// AccountNumber.
        /// </summary>
        [EnumMember(Value = "account_number")]
        AccountNumber,

        /// <summary>
        /// Email.
        /// </summary>
        [EnumMember(Value = "email")]
        Email,

        /// <summary>
        /// CompanyName.
        /// </summary>
        [EnumMember(Value = "company_name")]
        CompanyName,

        /// <summary>
        /// Address.
        /// </summary>
        [EnumMember(Value = "address")]
        Address,

        /// <summary>
        /// City.
        /// </summary>
        [EnumMember(Value = "city")]
        City,

        /// <summary>
        /// State.
        /// </summary>
        [EnumMember(Value = "state")]
        State,

        /// <summary>
        /// Zip.
        /// </summary>
        [EnumMember(Value = "zip")]
        Zip,

        /// <summary>
        /// HomePhone.
        /// </summary>
        [EnumMember(Value = "home_phone")]
        HomePhone,

        /// <summary>
        /// OfficePhone.
        /// </summary>
        [EnumMember(Value = "office_phone")]
        OfficePhone,

        /// <summary>
        /// OfficeExtPhone.
        /// </summary>
        [EnumMember(Value = "office_ext_phone")]
        OfficeExtPhone,

        /// <summary>
        /// CellPhone.
        /// </summary>
        [EnumMember(Value = "cell_phone")]
        CellPhone,

        /// <summary>
        /// ContactApiId.
        /// </summary>
        [EnumMember(Value = "contact_api_id")]
        ContactApiId,

        /// <summary>
        /// DateOfBirth.
        /// </summary>
        [EnumMember(Value = "date_of_birth")]
        DateOfBirth,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}