// <copyright file="RejectedTransactionAchRetry.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// RejectedTransactionAchRetry.
    /// </summary>
    public class RejectedTransactionAchRetry
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private int? returnFee;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "return_fee", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="RejectedTransactionAchRetry"/> class.
        /// </summary>
        public RejectedTransactionAchRetry()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RejectedTransactionAchRetry"/> class.
        /// </summary>
        /// <param name="rejectedTransactionId">rejected_transaction_id.</param>
        /// <param name="returnFee">return_fee.</param>
        /// <param name="id">id.</param>
        /// <param name="retryTransactionId">retry_transaction_id.</param>
        /// <param name="returnFeeTransactionId">return_fee_transaction_id.</param>
        /// <param name="createdTs">created_ts.</param>
        /// <param name="createdUserId">created_user_id.</param>
        public RejectedTransactionAchRetry(
            string rejectedTransactionId = null,
            int? returnFee = null,
            string id = null,
            string retryTransactionId = null,
            string returnFeeTransactionId = null,
            int? createdTs = null,
            string createdUserId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.RejectedTransactionId = rejectedTransactionId;

            if (returnFee != null)
            {
                this.ReturnFee = returnFee;
            }
            this.Id = id;
            this.RetryTransactionId = retryTransactionId;
            this.ReturnFeeTransactionId = returnFeeTransactionId;
            this.CreatedTs = createdTs;
            this.CreatedUserId = createdUserId;
        }

        /// <summary>
        /// Rejected Transaction ID.
        /// </summary>
        [JsonProperty("rejected_transaction_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RejectedTransactionId { get; set; }

        /// <summary>
        /// Return Fee.
        /// </summary>
        [JsonProperty("return_fee")]
        public int? ReturnFee
        {
            get
            {
                return this.returnFee;
            }

            set
            {
                this.shouldSerialize["return_fee"] = true;
                this.returnFee = value;
            }
        }

        /// <summary>
        /// Transaction ACH Retry ID.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Retry Transaction ID.
        /// </summary>
        [JsonProperty("retry_transaction_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RetryTransactionId { get; set; }

        /// <summary>
        /// Return Fee Transaction ID.
        /// </summary>
        [JsonProperty("return_fee_transaction_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ReturnFeeTransactionId { get; set; }

        /// <summary>
        /// Created Time Stamp
        /// </summary>
        [JsonProperty("created_ts", NullValueHandling = NullValueHandling.Ignore)]
        public int? CreatedTs { get; set; }

        /// <summary>
        /// User ID Created the register
        /// </summary>
        [JsonProperty("created_user_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedUserId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RejectedTransactionAchRetry : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetReturnFee()
        {
            this.shouldSerialize["return_fee"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeReturnFee()
        {
            return this.shouldSerialize["return_fee"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RejectedTransactionAchRetry other &&
                (this.RejectedTransactionId == null && other.RejectedTransactionId == null ||
                 this.RejectedTransactionId?.Equals(other.RejectedTransactionId) == true) &&
                (this.ReturnFee == null && other.ReturnFee == null ||
                 this.ReturnFee?.Equals(other.ReturnFee) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.RetryTransactionId == null && other.RetryTransactionId == null ||
                 this.RetryTransactionId?.Equals(other.RetryTransactionId) == true) &&
                (this.ReturnFeeTransactionId == null && other.ReturnFeeTransactionId == null ||
                 this.ReturnFeeTransactionId?.Equals(other.ReturnFeeTransactionId) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                (this.CreatedUserId == null && other.CreatedUserId == null ||
                 this.CreatedUserId?.Equals(other.CreatedUserId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RejectedTransactionId = {this.RejectedTransactionId ?? "null"}");
            toStringOutput.Add($"ReturnFee = {(this.ReturnFee == null ? "null" : this.ReturnFee.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"RetryTransactionId = {this.RetryTransactionId ?? "null"}");
            toStringOutput.Add($"ReturnFeeTransactionId = {this.ReturnFeeTransactionId ?? "null"}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");
            toStringOutput.Add($"CreatedUserId = {this.CreatedUserId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}