// <copyright file="ResponseContactSearchsCollection.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ResponseContactSearchsCollection.
    /// </summary>
    public class ResponseContactSearchsCollection : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseContactSearchsCollection"/> class.
        /// </summary>
        public ResponseContactSearchsCollection()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseContactSearchsCollection"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="list">list.</param>
        /// <param name="links">links.</param>
        /// <param name="pagination">pagination.</param>
        /// <param name="sort">sort.</param>
        public ResponseContactSearchsCollection(
            Models.Type6Enum? type = Models.Type6Enum.ContactSearchsCollection,
            List<Models.List1> list = null,
            Models.Links links = null,
            Models.Pagination pagination = null,
            Models.Sort sort = null)
        {
            this.Type = type;
            this.List = list;
            this.Links = links;
            this.Pagination = pagination;
            this.Sort = sort;
        }

        /// <summary>
        /// Resource Type
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type6Enum? Type { get; set; }

        /// <summary>
        /// Resource Members
        /// </summary>
        [JsonProperty("list", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.List1> List { get; set; }

        /// <summary>
        /// Pagination page links
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Links Links { get; set; }

        /// <summary>
        /// Pagination info
        /// </summary>
        [JsonProperty("pagination", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Pagination Pagination { get; set; }

        /// <summary>
        /// Sort information used on the results
        /// </summary>
        [JsonProperty("sort", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Sort Sort { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ResponseContactSearchsCollection : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ResponseContactSearchsCollection other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.List == null && other.List == null ||
                 this.List?.Equals(other.List) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true) &&
                (this.Pagination == null && other.Pagination == null ||
                 this.Pagination?.Equals(other.Pagination) == true) &&
                (this.Sort == null && other.Sort == null ||
                 this.Sort?.Equals(other.Sort) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"List = {(this.List == null ? "null" : $"[{string.Join(", ", this.List)} ]")}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");
            toStringOutput.Add($"Pagination = {(this.Pagination == null ? "null" : this.Pagination.ToString())}");
            toStringOutput.Add($"Sort = {(this.Sort == null ? "null" : this.Sort.ToString())}");

            base.ToString(toStringOutput);
        }
    }
}