// <copyright file="SchemeId.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// SchemeId.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum SchemeId
    {
        /// <summary>
        /// Visa.
        /// </summary>
        [EnumMember(Value = "Visa")]
        Visa,

        /// <summary>
        /// Mastercard.
        /// </summary>
        [EnumMember(Value = "Mastercard")]
        Mastercard,

        /// <summary>
        /// EnumAmericanExpress.
        /// </summary>
        [EnumMember(Value = "American Express")]
        EnumAmericanExpress,

        /// <summary>
        /// Diners.
        /// </summary>
        [EnumMember(Value = "Diners")]
        Diners,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}