// <copyright file="SmsBlacklist.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// SmsBlacklist.
    /// </summary>
    public class SmsBlacklist : BaseModel
    {
        private string id;
        private int? createdTs;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "id", false },
            { "created_ts", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsBlacklist"/> class.
        /// </summary>
        public SmsBlacklist()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsBlacklist"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="isBlacklisted">isBlacklisted.</param>
        /// <param name="detail">detail.</param>
        /// <param name="createdTs">created_ts.</param>
        public SmsBlacklist(
            string id = null,
            bool? isBlacklisted = null,
            bool? detail = null,
            int? createdTs = null)
        {

            if (id != null)
            {
                this.Id = id;
            }
            this.IsBlacklisted = isBlacklisted;
            this.Detail = detail;

            if (createdTs != null)
            {
                this.CreatedTs = createdTs;
            }
        }

        /// <summary>
        /// Blacklist ID
        /// </summary>
        [JsonProperty("id")]
        public string Id
        {
            get
            {
                return this.id;
            }

            set
            {
                this.shouldSerialize["id"] = true;
                this.id = value;
            }
        }

        /// <summary>
        /// isBlacklisted
        /// </summary>
        [JsonProperty("isBlacklisted", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsBlacklisted { get; set; }

        /// <summary>
        /// Contact Id
        /// </summary>
        [JsonProperty("detail", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Detail { get; set; }

        /// <summary>
        /// Created Time Stamp
        /// </summary>
        [JsonProperty("created_ts")]
        public int? CreatedTs
        {
            get
            {
                return this.createdTs;
            }

            set
            {
                this.shouldSerialize["created_ts"] = true;
                this.createdTs = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SmsBlacklist : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetId()
        {
            this.shouldSerialize["id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCreatedTs()
        {
            this.shouldSerialize["created_ts"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeId()
        {
            return this.shouldSerialize["id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCreatedTs()
        {
            return this.shouldSerialize["created_ts"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SmsBlacklist other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.IsBlacklisted == null && other.IsBlacklisted == null ||
                 this.IsBlacklisted?.Equals(other.IsBlacklisted) == true) &&
                (this.Detail == null && other.Detail == null ||
                 this.Detail?.Equals(other.Detail) == true) &&
                (this.CreatedTs == null && other.CreatedTs == null ||
                 this.CreatedTs?.Equals(other.CreatedTs) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"IsBlacklisted = {(this.IsBlacklisted == null ? "null" : this.IsBlacklisted.ToString())}");
            toStringOutput.Add($"Detail = {(this.Detail == null ? "null" : this.Detail.ToString())}");
            toStringOutput.Add($"CreatedTs = {(this.CreatedTs == null ? "null" : this.CreatedTs.ToString())}");

            base.ToString(toStringOutput);
        }
    }
}