// <copyright file="Status5.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Status5.
    /// </summary>
    public class Status5 : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Status5"/> class.
        /// </summary>
        public Status5()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Status5"/> class.
        /// </summary>
        /// <param name="responseCode">response_code.</param>
        public Status5(
            string responseCode = null)
        {
            this.ResponseCode = responseCode;
        }

        /// <summary>
        /// Response code for API response.
        /// </summary>
        [JsonProperty("response_code", NullValueHandling = NullValueHandling.Ignore)]
        public string ResponseCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Status5 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Status5 other &&
                (this.ResponseCode == null && other.ResponseCode == null ||
                 this.ResponseCode?.Equals(other.ResponseCode) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ResponseCode = {this.ResponseCode ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}