// <copyright file="TerminalManufacturerCodeEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// TerminalManufacturerCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TerminalManufacturerCodeEnum
    {
        /// <summary>
        /// Enum1.
        /// </summary>
        [EnumMember(Value = "1")]
        Enum1,

        /// <summary>
        /// Enum2.
        /// </summary>
        [EnumMember(Value = "2")]
        Enum2,

        /// <summary>
        /// Enum4.
        /// </summary>
        [EnumMember(Value = "4")]
        Enum4,

        /// <summary>
        /// Enum100.
        /// </summary>
        [EnumMember(Value = "100")]
        Enum100
    }
}