// <copyright file="ThreeDsRequestorPriorAuthenticationInfo.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ThreeDsRequestorPriorAuthenticationInfo.
    /// </summary>
    public class ThreeDsRequestorPriorAuthenticationInfo : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestorPriorAuthenticationInfo"/> class.
        /// </summary>
        public ThreeDsRequestorPriorAuthenticationInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestorPriorAuthenticationInfo"/> class.
        /// </summary>
        /// <param name="threeDsReqPriorRef">three_ds_req_prior_ref.</param>
        /// <param name="threeDsReqPriorAuthMethod">three_ds_req_prior_auth_method.</param>
        /// <param name="threeDsReqPriorAuthTimestamp">three_ds_req_prior_auth_timestamp.</param>
        /// <param name="threeDsReqPriorAuthData">three_ds_req_prior_auth_data.</param>
        public ThreeDsRequestorPriorAuthenticationInfo(
            string threeDsReqPriorRef = null,
            Models.ThreeDsReqPriorAuthMethodEnum? threeDsReqPriorAuthMethod = null,
            string threeDsReqPriorAuthTimestamp = null,
            string threeDsReqPriorAuthData = null)
        {
            this.ThreeDsReqPriorRef = threeDsReqPriorRef;
            this.ThreeDsReqPriorAuthMethod = threeDsReqPriorAuthMethod;
            this.ThreeDsReqPriorAuthTimestamp = threeDsReqPriorAuthTimestamp;
            this.ThreeDsReqPriorAuthData = threeDsReqPriorAuthData;
        }

        /// <summary>
        /// This data element provides additional information to the ACS to determine the best approach for handling a request. The field is limited to 36 characters containing ACS Transaction ID for a prior authenticated transaction (for example, the first recurring transaction that was authenticated with the cardholder).
        /// </summary>
        [JsonProperty("three_ds_req_prior_ref", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDsReqPriorRef { get; set; }

        /// <summary>
        /// Mechanism used by the Cardholder to previously authenticate to the 3DS Requestor.
        /// >01 - Frictionless authentication occurred by ACS
        /// >
        /// >02 - Cardholder challenge occurred by ACS
        /// >
        /// >03 - AVS verified
        /// >
        /// >04 - Other issuer methods
        /// >
        /// >80 through 99 - PS-specific value (dependent on the payment scheme type).
        /// >
        /// </summary>
        [JsonProperty("three_ds_req_prior_auth_method", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDsReqPriorAuthMethodEnum? ThreeDsReqPriorAuthMethod { get; set; }

        /// <summary>
        /// Date and time converted into UTC of the prior authentication. Accepted date format is YYYYMMDDHHMM.
        /// </summary>
        [JsonProperty("three_ds_req_prior_auth_timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDsReqPriorAuthTimestamp { get; set; }

        /// <summary>
        /// Data that documents and supports a specific authentication process. In the current version of the specification this data element is not defined in detail, however the intention is that for each 3DS Requestor Authentication Method, this field carry data that the ACS can use to verify the authentication process. In future versions of the application, these details are expected to be included.
        /// </summary>
        [JsonProperty("three_ds_req_prior_auth_data", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDsReqPriorAuthData { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDsRequestorPriorAuthenticationInfo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ThreeDsRequestorPriorAuthenticationInfo other &&
                (this.ThreeDsReqPriorRef == null && other.ThreeDsReqPriorRef == null ||
                 this.ThreeDsReqPriorRef?.Equals(other.ThreeDsReqPriorRef) == true) &&
                (this.ThreeDsReqPriorAuthMethod == null && other.ThreeDsReqPriorAuthMethod == null ||
                 this.ThreeDsReqPriorAuthMethod?.Equals(other.ThreeDsReqPriorAuthMethod) == true) &&
                (this.ThreeDsReqPriorAuthTimestamp == null && other.ThreeDsReqPriorAuthTimestamp == null ||
                 this.ThreeDsReqPriorAuthTimestamp?.Equals(other.ThreeDsReqPriorAuthTimestamp) == true) &&
                (this.ThreeDsReqPriorAuthData == null && other.ThreeDsReqPriorAuthData == null ||
                 this.ThreeDsReqPriorAuthData?.Equals(other.ThreeDsReqPriorAuthData) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ThreeDsReqPriorRef = {this.ThreeDsReqPriorRef ?? "null"}");
            toStringOutput.Add($"ThreeDsReqPriorAuthMethod = {(this.ThreeDsReqPriorAuthMethod == null ? "null" : this.ThreeDsReqPriorAuthMethod.ToString())}");
            toStringOutput.Add($"ThreeDsReqPriorAuthTimestamp = {this.ThreeDsReqPriorAuthTimestamp ?? "null"}");
            toStringOutput.Add($"ThreeDsReqPriorAuthData = {this.ThreeDsReqPriorAuthData ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}