// <copyright file="ThreeDsRequestor.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ThreeDsRequestor.
    /// </summary>
    public class ThreeDsRequestor : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestor"/> class.
        /// </summary>
        public ThreeDsRequestor()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestor"/> class.
        /// </summary>
        /// <param name="threeDsRequestorAuthenticationInd">three_ds_requestor_authentication_ind.</param>
        /// <param name="threeDsRequestorAuthenticationInfo">three_ds_requestor_authentication_info.</param>
        /// <param name="threeDsRequestorChallengeInd">three_ds_requestor_challenge_ind.</param>
        /// <param name="threeDsRequestorPriorAuthenticationInfo">three_ds_requestor_prior_authentication_info.</param>
        /// <param name="threeDsRequestorDecReqInd">three_ds_requestor_dec_req_ind.</param>
        /// <param name="threeDsRequestorDecMaxTime">three_ds_requestor_dec_max_time.</param>
        /// <param name="threeDsRequestorSpcSupport">three_ds_requestor_spc_support.</param>
        /// <param name="spcIncompInd">spc_incomp_ind.</param>
        public ThreeDsRequestor(
            Models.ThreeDsRequestorAuthenticationIndEnum threeDsRequestorAuthenticationInd,
            List<Models.ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo = null,
            List<Models.ThreeDsRequestorChallengeIndEnum> threeDsRequestorChallengeInd = null,
            List<Models.ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo = null,
            Models.ThreeDsRequestorDecReqIndEnum? threeDsRequestorDecReqInd = null,
            int? threeDsRequestorDecMaxTime = null,
            Models.ThreeDsRequestorSpcSupportEnum? threeDsRequestorSpcSupport = null,
            string spcIncompInd = null)
        {
            this.ThreeDsRequestorAuthenticationInd = threeDsRequestorAuthenticationInd;
            this.ThreeDsRequestorAuthenticationInfo = threeDsRequestorAuthenticationInfo;
            this.ThreeDsRequestorChallengeInd = threeDsRequestorChallengeInd;
            this.ThreeDsRequestorPriorAuthenticationInfo = threeDsRequestorPriorAuthenticationInfo;
            this.ThreeDsRequestorDecReqInd = threeDsRequestorDecReqInd;
            this.ThreeDsRequestorDecMaxTime = threeDsRequestorDecMaxTime;
            this.ThreeDsRequestorSpcSupport = threeDsRequestorSpcSupport;
            this.SpcIncompInd = spcIncompInd;
        }

        /// <summary>
        /// <![CDATA[
        /// Indicates the type of Authentication request. This data element provides additional information to the ACS to determine the best approach for handling an authentication request. This value is used for App-based and Browser flows.
        /// >01 - Payment transaction
        /// >
        /// >02 - Recurring transaction
        /// >
        /// >03 - Installment transaction
        /// >
        /// >04 - Add card
        /// >
        /// >05 - Maintain card
        /// >
        /// >06 - Cardholder verification as part of EMV token ID&V
        /// >
        /// >07 - Billing agreement
        /// >
        /// >80 through 99 - can be used for PS-specific values, regardless of protocol version
        /// >
        /// ]]>
        /// </summary>
        [JsonProperty("three_ds_requestor_authentication_ind")]
        public Models.ThreeDsRequestorAuthenticationIndEnum ThreeDsRequestorAuthenticationInd { get; set; }

        /// <summary>
        /// Information about how the 3DS Requestor authenticated the cardholder before or during the transaction.
        /// </summary>
        [JsonProperty("three_ds_requestor_authentication_info", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ThreeDsRequestorAuthenticationInfo> ThreeDsRequestorAuthenticationInfo { get; set; }

        /// <summary>
        /// Indicates whether a challenge is requested for this transaction. For example: For 01-PA, a 3DS Requestor may have concerns about the transaction, and request a challenge. For 02-NPA, a challenge may be necessary when adding a new card to a wallet.
        /// Values "05" through "09" are accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater (required protocol version can be set in the preferred_protocol_version field).
        /// If the element is not provided, the expected action is that the ACS would interpret as 01 (No preference).
        /// In versions prior to 2.3.1 only a single element is supported.  Starting from EMVCo version 2.3.1, this array can now support 1-2 elements.
        /// When providing two preferences, you must ensure that they are in preference order and are not conflicting. For example, 02 = No challenge requested and 04 = Challenge requested (Mandate).
        /// >01 - No preference
        /// >
        /// >02 - No challenge requested
        /// >
        /// >03 - Challenge requested: 3DS Requestor Preference
        /// >
        /// >04 - Challenge requested: Mandate
        /// >
        /// >05 - No challenge requested (transactional risk analysis is already performed) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >06 - No challenge requested (Data share only) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >07 - No challenge requested (strong consumer authentication is already performed) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >08 - No challenge requested (utilise whitelist exemption if no challenge required) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >09 - Challenge requested (whitelist prompt requested if challenge required) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >80 through 99 - can be used for PS-specific values, regardless of protocol version
        /// >
        /// </summary>
        [JsonProperty("three_ds_requestor_challenge_ind", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ThreeDsRequestorChallengeIndEnum> ThreeDsRequestorChallengeInd { get; set; }

        /// <summary>
        /// This object contains information about how the 3DS Requestor authenticated the cardholder as part of a previous 3DS transaction.
        /// In versions prior to 2.3.1, this array is limited to a size of 1.  Starting from EMVCo version 2.3.1 this array size may be 1-3.
        /// This field is optional, but recommended to include for versions prior to 2.3.1. From 2.3.1, it is required for 3RI in the case of Decoupled Authentication Fallback or for SPC.
        /// </summary>
        [JsonProperty("three_ds_requestor_prior_authentication_info", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ThreeDsRequestorPriorAuthenticationInfo> ThreeDsRequestorPriorAuthenticationInfo { get; set; }

        /// <summary>
        /// Indicates whether the 3DS Requestor requests the ACS to utilise Decoupled Authentication and agrees to utilise Decoupled Authentication if the ACS confirms its use.
        ///  Value "F" and "B" are only valid for EMV 3DS 2.3.1 or later.
        /// The field is optional and if value is not present, the expected action is for the ACS to interpret as "N".
        /// Available for supporting EMV 3DS 2.2.0 and later versions.
        /// >Y - Decoupled Authentication is supported and preferred if challenge is necessary.
        /// >
        /// >N - Do not use Decoupled Authentication.
        /// >
        /// >F - Decoupled Authentication is supported and is to be used only as a fallback challenge method if a challenge is necessary (Transaction Status = D in RReq). Available in EMV 3DS 2.3.1 and later.
        /// >
        /// >B - Decoupled Authentication is supported and can be used as a primary or fallback challenge method if a challenge is necessary (Transaction Status = D in either ARes or RReq). Available in EMV 3DS 2.3.1 and later.
        /// >
        /// </summary>
        [JsonProperty("three_ds_requestor_dec_req_ind", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDsRequestorDecReqIndEnum? ThreeDsRequestorDecReqInd { get; set; }

        /// <summary>
        /// Indicates the maximum amount of time that the 3DS Requestor will wait for an ACS to provide the results of a Decoupled Authentication transaction (in minutes). Valid values are between 1 and 10080.
        /// The field is optional and if value is not present, the expected action is for the ACS to interpret it as 10080 minutes (7 days).
        /// Available for supporting EMV 3DS 2.2.0 and later versions.
        /// Starting from EMV 3DS 2.3.1:
        /// This field is required if three_ds_requestor_dec_req_ind = Y, F or B
        /// </summary>
        [JsonProperty("three_ds_requestor_dec_max_time", NullValueHandling = NullValueHandling.Ignore)]
        public int? ThreeDsRequestorDecMaxTime { get; set; }

        /// <summary>
        /// Indicate if the 3DS Requestor supports the SPC authentication.
        /// This field is required if device_channel = 02 (BRW) and it is supported by the 3DS Requestor.
        /// Available for supporting EMV 3DS 2.3.1 and later versions.
        /// >Y - Supported
        /// >
        /// </summary>
        [JsonProperty("three_ds_requestor_spc_support", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDsRequestorSpcSupportEnum? ThreeDsRequestorSpcSupport { get; set; }

        /// <summary>
        /// Reason that the SPC authentication was not completed.
        /// This field is required if device_channel = 02 (BRW) and the 3DS Requestor attempts to invoke SPC API and there is an error. Available for supporting EMV 3DS 2.3.1 and later versions.
        /// </summary>
        [JsonProperty("spc_incomp_ind", NullValueHandling = NullValueHandling.Ignore)]
        public string SpcIncompInd { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDsRequestor : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ThreeDsRequestor other &&
                (this.ThreeDsRequestorAuthenticationInd.Equals(other.ThreeDsRequestorAuthenticationInd)) &&
                (this.ThreeDsRequestorAuthenticationInfo == null && other.ThreeDsRequestorAuthenticationInfo == null ||
                 this.ThreeDsRequestorAuthenticationInfo?.Equals(other.ThreeDsRequestorAuthenticationInfo) == true) &&
                (this.ThreeDsRequestorChallengeInd == null && other.ThreeDsRequestorChallengeInd == null ||
                 this.ThreeDsRequestorChallengeInd?.Equals(other.ThreeDsRequestorChallengeInd) == true) &&
                (this.ThreeDsRequestorPriorAuthenticationInfo == null && other.ThreeDsRequestorPriorAuthenticationInfo == null ||
                 this.ThreeDsRequestorPriorAuthenticationInfo?.Equals(other.ThreeDsRequestorPriorAuthenticationInfo) == true) &&
                (this.ThreeDsRequestorDecReqInd == null && other.ThreeDsRequestorDecReqInd == null ||
                 this.ThreeDsRequestorDecReqInd?.Equals(other.ThreeDsRequestorDecReqInd) == true) &&
                (this.ThreeDsRequestorDecMaxTime == null && other.ThreeDsRequestorDecMaxTime == null ||
                 this.ThreeDsRequestorDecMaxTime?.Equals(other.ThreeDsRequestorDecMaxTime) == true) &&
                (this.ThreeDsRequestorSpcSupport == null && other.ThreeDsRequestorSpcSupport == null ||
                 this.ThreeDsRequestorSpcSupport?.Equals(other.ThreeDsRequestorSpcSupport) == true) &&
                (this.SpcIncompInd == null && other.SpcIncompInd == null ||
                 this.SpcIncompInd?.Equals(other.SpcIncompInd) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ThreeDsRequestorAuthenticationInd = {this.ThreeDsRequestorAuthenticationInd}");
            toStringOutput.Add($"ThreeDsRequestorAuthenticationInfo = {(this.ThreeDsRequestorAuthenticationInfo == null ? "null" : $"[{string.Join(", ", this.ThreeDsRequestorAuthenticationInfo)} ]")}");
            toStringOutput.Add($"ThreeDsRequestorChallengeInd = {(this.ThreeDsRequestorChallengeInd == null ? "null" : $"[{string.Join(", ", this.ThreeDsRequestorChallengeInd)} ]")}");
            toStringOutput.Add($"ThreeDsRequestorPriorAuthenticationInfo = {(this.ThreeDsRequestorPriorAuthenticationInfo == null ? "null" : $"[{string.Join(", ", this.ThreeDsRequestorPriorAuthenticationInfo)} ]")}");
            toStringOutput.Add($"ThreeDsRequestorDecReqInd = {(this.ThreeDsRequestorDecReqInd == null ? "null" : this.ThreeDsRequestorDecReqInd.ToString())}");
            toStringOutput.Add($"ThreeDsRequestorDecMaxTime = {(this.ThreeDsRequestorDecMaxTime == null ? "null" : this.ThreeDsRequestorDecMaxTime.ToString())}");
            toStringOutput.Add($"ThreeDsRequestorSpcSupport = {(this.ThreeDsRequestorSpcSupport == null ? "null" : this.ThreeDsRequestorSpcSupport.ToString())}");
            toStringOutput.Add($"SpcIncompInd = {this.SpcIncompInd ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}