// <copyright file="ThreeDsRequestorAuthenticationInfo.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ThreeDsRequestorAuthenticationInfo.
    /// </summary>
    public class ThreeDsRequestorAuthenticationInfo : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestorAuthenticationInfo"/> class.
        /// </summary>
        public ThreeDsRequestorAuthenticationInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRequestorAuthenticationInfo"/> class.
        /// </summary>
        /// <param name="threeDsReqAuthMethod">three_ds_req_auth_method.</param>
        /// <param name="threeDsReqAuthTimestamp">three_ds_req_auth_timestamp.</param>
        /// <param name="threeDsReqAuthData">three_ds_req_auth_data.</param>
        public ThreeDsRequestorAuthenticationInfo(
            Models.ThreeDsReqAuthMethodEnum? threeDsReqAuthMethod = null,
            string threeDsReqAuthTimestamp = null,
            string threeDsReqAuthData = null)
        {
            this.ThreeDsReqAuthMethod = threeDsReqAuthMethod;
            this.ThreeDsReqAuthTimestamp = threeDsReqAuthTimestamp;
            this.ThreeDsReqAuthData = threeDsReqAuthData;
        }

        /// <summary>
        /// Mechanism used by the Cardholder to authenticate to the 3DS Requestor. "07" and "08" are accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater (required protocol version can be set in the preferred_protocol_version field)
        /// >01 - No 3DS Requestor authentication occurred (i.e. cardholder "logged in" as guest)
        /// >
        /// >02 - Login to the cardholder account at the 3DS Requestor system using 3DS Requestor's own credentials
        /// >
        /// >03 - Login to the cardholder account at the 3DS Requestor system using federated ID
        /// >
        /// >04 - Login to the cardholder account at the 3DS Requestor system using issuer credentials
        /// >
        /// >05 - Login to the cardholder account at the 3DS Requestor system using third-party authentication
        /// >
        /// >06 - Login to the cardholder account at the 3DS Requestor system using FIDO Authenticator
        /// >
        /// >07 - Login to the cardholder account at the 3DS Requestor system using FIDO Authenticator (FIDO assurance data signed) (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >08 - SRC Assurance Data (EMV 3DS 2.2.0 version or greater)
        /// >
        /// >80 through 99 - can be used for PS-specific values, regardless of protocol version
        /// >
        /// </summary>
        [JsonProperty("three_ds_req_auth_method", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDsReqAuthMethodEnum? ThreeDsReqAuthMethod { get; set; }

        /// <summary>
        /// Date and time converted into UTC of the cardholder authentication. Field is limited to 12 characters and accepted format is YYYYMMDDHHMM
        /// </summary>
        [JsonProperty("three_ds_req_auth_timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDsReqAuthTimestamp { get; set; }

        /// <summary>
        /// Stringified array of objects that documents and supports a specific authentication process. In the current version of the specification, this data element is not defined in detail, however the intention is that for each 3DS Requestor Authentication Method, this field carry data that the ACS can use to verify the authentication process. For example, if the 3DS
        /// Requestor Authentication Method is:
        /// 03 -> then this element can carry information about the provider of the federated ID and related information
        /// 06 -> then this element can carry the FIDO attestation data (incl. the signature)
        /// 07 -> then this element can carry FIDO Attestation data with the FIDO assurance data signed.
        /// 08 -> then this element can carry the SRC assurance data.
        /// In versions prior to 2.3.1, this array is limited to a single object.
        /// Starting from EMVCo version 2.3.1, the array may have 1-3 elements.
        /// This field is optional, but recommended to include.
        /// </summary>
        [JsonProperty("three_ds_req_auth_data", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDsReqAuthData { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDsRequestorAuthenticationInfo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ThreeDsRequestorAuthenticationInfo other &&
                (this.ThreeDsReqAuthMethod == null && other.ThreeDsReqAuthMethod == null ||
                 this.ThreeDsReqAuthMethod?.Equals(other.ThreeDsReqAuthMethod) == true) &&
                (this.ThreeDsReqAuthTimestamp == null && other.ThreeDsReqAuthTimestamp == null ||
                 this.ThreeDsReqAuthTimestamp?.Equals(other.ThreeDsReqAuthTimestamp) == true) &&
                (this.ThreeDsReqAuthData == null && other.ThreeDsReqAuthData == null ||
                 this.ThreeDsReqAuthData?.Equals(other.ThreeDsReqAuthData) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ThreeDsReqAuthMethod = {(this.ThreeDsReqAuthMethod == null ? "null" : this.ThreeDsReqAuthMethod.ToString())}");
            toStringOutput.Add($"ThreeDsReqAuthTimestamp = {this.ThreeDsReqAuthTimestamp ?? "null"}");
            toStringOutput.Add($"ThreeDsReqAuthData = {this.ThreeDsReqAuthData ?? "null"}");

            base.ToString(toStringOutput);
        }
    }
}