// <copyright file="TransactionType.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// TransactionType.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum TransactionType
    {
        /// <summary>
        /// Enum01.
        /// </summary>
        [EnumMember(Value = "01")]
        Enum01,

        /// <summary>
        /// Enum03.
        /// </summary>
        [EnumMember(Value = "03")]
        Enum03,

        /// <summary>
        /// Enum10.
        /// </summary>
        [EnumMember(Value = "10")]
        Enum10,

        /// <summary>
        /// Enum11.
        /// </summary>
        [EnumMember(Value = "11")]
        Enum11,

        /// <summary>
        /// Enum28.
        /// </summary>
        [EnumMember(Value = "28")]
        Enum28,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}