// <copyright file="Type130Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Type130Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type130Enum
    {
        /// <summary>
        /// UsersCollection.
        /// </summary>
        [EnumMember(Value = "UsersCollection")]
        UsersCollection
    }
}