// <copyright file="Type47.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Type47.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Type47
    {
        /// <summary>
        /// MerchantDeposit.
        /// </summary>
        [EnumMember(Value = "MerchantDeposit")]
        MerchantDeposit,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}