// <copyright file="TypeIdEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// TypeIdEnum.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum TypeIdEnum
    {
        /// <summary>
        /// Enum20.
        /// </summary>
        Enum20 = 20,

        /// <summary>
        /// Enum21.
        /// </summary>
        Enum21 = 21,

        /// <summary>
        /// Enum22.
        /// </summary>
        Enum22 = 22,

        /// <summary>
        /// Enum30.
        /// </summary>
        Enum30 = 30,

        /// <summary>
        /// Enum40.
        /// </summary>
        Enum40 = 40,

        /// <summary>
        /// Enum50.
        /// </summary>
        Enum50 = 50
    }
}