// <copyright file="Type123Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Type123Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type123Enum
    {
        /// <summary>
        /// UserVerification.
        /// </summary>
        [EnumMember(Value = "UserVerification")]
        UserVerification
    }
}