// <copyright file="Type110Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Type110Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type110Enum
    {
        /// <summary>
        /// Transaction.
        /// </summary>
        [EnumMember(Value = "Transaction")]
        Transaction
    }
}