// <copyright file="Type138Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Type138Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type138Enum
    {
        /// <summary>
        /// Webhook.
        /// </summary>
        [EnumMember(Value = "Webhook")]
        Webhook
    }
}