// <copyright file="UiPrefs.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// UiPrefs.
    /// </summary>
    public class UiPrefs
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string entryPage;
        private int? pageSize;
        private string defaultTerminal;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "entry_page", false },
            { "page_size", false },
            { "default_terminal", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="UiPrefs"/> class.
        /// </summary>
        public UiPrefs()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UiPrefs"/> class.
        /// </summary>
        /// <param name="entryPage">entry_page.</param>
        /// <param name="pageSize">page_size.</param>
        /// <param name="reportExportType">report_export_type.</param>
        /// <param name="processMethod">process_method.</param>
        /// <param name="defaultTerminal">default_terminal.</param>
        public UiPrefs(
            string entryPage = null,
            int? pageSize = null,
            object reportExportType = null,
            object processMethod = null,
            string defaultTerminal = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (entryPage != null)
            {
                this.EntryPage = entryPage;
            }

            if (pageSize != null)
            {
                this.PageSize = pageSize;
            }
            this.ReportExportType = reportExportType;
            this.ProcessMethod = processMethod;

            if (defaultTerminal != null)
            {
                this.DefaultTerminal = defaultTerminal;
            }
        }

        /// <summary>
        /// Ui Prefs Entry Page
        /// </summary>
        [JsonProperty("entry_page")]
        public string EntryPage
        {
            get
            {
                return this.entryPage;
            }

            set
            {
                this.shouldSerialize["entry_page"] = true;
                this.entryPage = value;
            }
        }

        /// <summary>
        /// Ui Prefs Page Size
        /// </summary>
        [JsonProperty("page_size")]
        public int? PageSize
        {
            get
            {
                return this.pageSize;
            }

            set
            {
                this.shouldSerialize["page_size"] = true;
                this.pageSize = value;
            }
        }

        /// <summary>
        /// Gets or sets ReportExportType.
        /// </summary>
        [JsonProperty("report_export_type", NullValueHandling = NullValueHandling.Ignore)]
        public object ReportExportType { get; set; }

        /// <summary>
        /// Gets or sets ProcessMethod.
        /// </summary>
        [JsonProperty("process_method", NullValueHandling = NullValueHandling.Ignore)]
        public object ProcessMethod { get; set; }

        /// <summary>
        /// Ui Prefs Default Termianl
        /// </summary>
        [JsonProperty("default_terminal")]
        public string DefaultTerminal
        {
            get
            {
                return this.defaultTerminal;
            }

            set
            {
                this.shouldSerialize["default_terminal"] = true;
                this.defaultTerminal = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UiPrefs : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEntryPage()
        {
            this.shouldSerialize["entry_page"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPageSize()
        {
            this.shouldSerialize["page_size"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDefaultTerminal()
        {
            this.shouldSerialize["default_terminal"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEntryPage()
        {
            return this.shouldSerialize["entry_page"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePageSize()
        {
            return this.shouldSerialize["page_size"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDefaultTerminal()
        {
            return this.shouldSerialize["default_terminal"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UiPrefs other &&
                (this.EntryPage == null && other.EntryPage == null ||
                 this.EntryPage?.Equals(other.EntryPage) == true) &&
                (this.PageSize == null && other.PageSize == null ||
                 this.PageSize?.Equals(other.PageSize) == true) &&
                (this.ReportExportType == null && other.ReportExportType == null ||
                 this.ReportExportType?.Equals(other.ReportExportType) == true) &&
                (this.ProcessMethod == null && other.ProcessMethod == null ||
                 this.ProcessMethod?.Equals(other.ProcessMethod) == true) &&
                (this.DefaultTerminal == null && other.DefaultTerminal == null ||
                 this.DefaultTerminal?.Equals(other.DefaultTerminal) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EntryPage = {this.EntryPage ?? "null"}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");
            toStringOutput.Add($"ReportExportType = {(this.ReportExportType == null ? "null" : this.ReportExportType.ToString())}");
            toStringOutput.Add($"ProcessMethod = {(this.ProcessMethod == null ? "null" : this.ProcessMethod.ToString())}");
            toStringOutput.Add($"DefaultTerminal = {this.DefaultTerminal ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}