// <copyright file="V1TransactionsLevel3MasterCardRequest.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// V1TransactionsLevel3MasterCardRequest.
    /// </summary>
    public class V1TransactionsLevel3MasterCardRequest : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TransactionsLevel3MasterCardRequest"/> class.
        /// </summary>
        public V1TransactionsLevel3MasterCardRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1TransactionsLevel3MasterCardRequest"/> class.
        /// </summary>
        /// <param name="level3Data">level3_data.</param>
        public V1TransactionsLevel3MasterCardRequest(
            Models.Level3Data5 level3Data)
        {
            this.Level3Data = level3Data;
        }

        /// <summary>
        /// Level 3 data object
        /// </summary>
        [JsonProperty("level3_data")]
        public Models.Level3Data5 Level3Data { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"V1TransactionsLevel3MasterCardRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is V1TransactionsLevel3MasterCardRequest other &&
                (this.Level3Data == null && other.Level3Data == null ||
                 this.Level3Data?.Equals(other.Level3Data) == true) &&
                base.Equals(obj);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Level3Data = {(this.Level3Data == null ? "null" : this.Level3Data.ToString())}");

            base.ToString(toStringOutput);
        }
    }
}