// <copyright file="V1WalletProviderApplePayValidateMerchantRequest.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using FortisApi.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// V1WalletProviderApplePayValidateMerchantRequest.
    /// </summary>
    public class V1WalletProviderApplePayValidateMerchantRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1WalletProviderApplePayValidateMerchantRequest"/> class.
        /// </summary>
        public V1WalletProviderApplePayValidateMerchantRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1WalletProviderApplePayValidateMerchantRequest"/> class.
        /// </summary>
        /// <param name="url">url.</param>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="domainName">domainName.</param>
        /// <param name="displayName">displayName.</param>
        public V1WalletProviderApplePayValidateMerchantRequest(
            string url,
            string merchantId,
            string domainName,
            string displayName)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Url = url;
            this.MerchantId = merchantId;
            this.DomainName = domainName;
            this.DisplayName = displayName;
        }

        /// <summary>
        /// Url obtained in the ApplePay button click event. Apple's URL that needs to be called to validate merchant.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }

        /// <summary>
        /// Merchant ID
        /// </summary>
        [JsonProperty("merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// Domain Name
        /// </summary>
        [JsonProperty("domainName")]
        public string DomainName { get; set; }

        /// <summary>
        /// Title
        /// </summary>
        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"V1WalletProviderApplePayValidateMerchantRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is V1WalletProviderApplePayValidateMerchantRequest other &&
                (this.Url == null && other.Url == null ||
                 this.Url?.Equals(other.Url) == true) &&
                (this.MerchantId == null && other.MerchantId == null ||
                 this.MerchantId?.Equals(other.MerchantId) == true) &&
                (this.DomainName == null && other.DomainName == null ||
                 this.DomainName?.Equals(other.DomainName) == true) &&
                (this.DisplayName == null && other.DisplayName == null ||
                 this.DisplayName?.Equals(other.DisplayName) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"MerchantId = {this.MerchantId ?? "null"}");
            toStringOutput.Add($"DomainName = {this.DomainName ?? "null"}");
            toStringOutput.Add($"DisplayName = {this.DisplayName ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}