// <copyright file="Values51Enum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// Values51Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Values51Enum
    {
        /// <summary>
        /// AccountNumber.
        /// </summary>
        [EnumMember(Value = "account_number")]
        AccountNumber,

        /// <summary>
        /// AccountHolderName.
        /// </summary>
        [EnumMember(Value = "account_holder_name")]
        AccountHolderName,

        /// <summary>
        /// RoutingNumber.
        /// </summary>
        [EnumMember(Value = "routing_number")]
        RoutingNumber
    }
}