// <copyright file="ValuesEnum.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisAPI.Standard.Models
{
    /// <summary>
    /// ValuesEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValuesEnum
    {
        /// <summary>
        /// AccountVaultId.
        /// </summary>
        [EnumMember(Value = "account_vault_id")]
        AccountVaultId,

        /// <summary>
        /// TokenId.
        /// </summary>
        [EnumMember(Value = "token_id")]
        TokenId,

        /// <summary>
        /// AccountVaultApiId.
        /// </summary>
        [EnumMember(Value = "account_vault_api_id")]
        AccountVaultApiId,

        /// <summary>
        /// TokenApiId.
        /// </summary>
        [EnumMember(Value = "token_api_id")]
        TokenApiId
    }
}