// <copyright file="Values99.cs" company="APIMatic">
// FortisApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace FortisApi.Standard.Models
{
    /// <summary>
    /// Values99.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Values99
    {
        /// <summary>
        /// PreviousTransactionId.
        /// </summary>
        [EnumMember(Value = "previous_transaction_id")]
        PreviousTransactionId,

        /// <summary>
        /// PreviousTransactionApiId.
        /// </summary>
        [EnumMember(Value = "previous_transaction_api_id")]
        PreviousTransactionApiId,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}