// <copyright file="FilterByOperator.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace FortisAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<FilterByOperator>),
        new[] {
            typeof(Operator1Case)
        },
        true
    )]
    public abstract class FilterByOperator
    {
        /// <summary>
        /// This is Operator1 case.
        /// </summary>
        /// <returns>
        /// The FilterByOperator instance, wrapping the provided Operator1Enum value.
        /// </returns>
        public static FilterByOperator FromOperator1(Operator1Enum operator1)
        {
            return new Operator1Case().Set(operator1);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<Operator1Enum, T> operator1);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<Operator1Enum, T> operator1 = null) =>
                Match(operator1);

        [JsonConverter(typeof(UnionTypeCaseConverter<Operator1Case, Operator1Enum>))]
        private sealed class Operator1Case : FilterByOperator, ICaseValue<Operator1Case, Operator1Enum>
        {
            public Operator1Enum Value;

            public override T Match<T>(Func<Operator1Enum, T> operator1) =>
                   operator1 != null ? operator1(Value) : default;

            public Operator1Case Set(Operator1Enum value)
            {
                Value = value;
                return this;
            }

            public Operator1Enum Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is Operator1Case other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value.Equals(other.Value); 
            }
        }
    }
}