// <copyright file="FilterByValueCase1.cs" company="APIMatic">
// FortisAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace FortisAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<FilterByValueCase1>),
        new[] {
            typeof(PrecisionCase),
            typeof(MStringCase),
            typeof(BooleanCase)
        },
        false
    )]
    public abstract class FilterByValueCase1
    {
        /// <summary>
        /// This is Precision case.
        /// </summary>
        /// <returns>
        /// The FilterByValueCase1 instance, wrapping the provided double value.
        /// </returns>
        public static FilterByValueCase1 FromPrecision(double precision)
        {
            return new PrecisionCase().Set(precision);
        }

        /// <summary>
        /// This is String case.
        /// </summary>
        /// <returns>
        /// The FilterByValueCase1 instance, wrapping the provided string value.
        /// </returns>
        public static FilterByValueCase1 FromString(string mString)
        {
            return new MStringCase().Set(mString);
        }

        /// <summary>
        /// This is Boolean case.
        /// </summary>
        /// <returns>
        /// The FilterByValueCase1 instance, wrapping the provided bool value.
        /// </returns>
        public static FilterByValueCase1 FromBoolean(bool boolean)
        {
            return new BooleanCase().Set(boolean);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<double, T> precision,
            Func<string, T> mString,
            Func<bool, T> boolean);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<double, T> precision = null,
            Func<string, T> mString = null,
            Func<bool, T> boolean = null) =>
                Match(precision, mString, boolean);

        [JsonConverter(typeof(UnionTypeCaseConverter<PrecisionCase, double>), JTokenType.Float)]
        private sealed class PrecisionCase : FilterByValueCase1, ICaseValue<PrecisionCase, double>
        {
            public double Value;

            public override T Match<T>(
                Func<double, T> precision,
                Func<string, T> mString,
                Func<bool, T> boolean) =>
                   precision != null ? precision(Value) : default;

            public PrecisionCase Set(double value)
            {
                Value = value;
                return this;
            }

            public double Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is PrecisionCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value.Equals(other.Value); 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<MStringCase, string>), JTokenType.String, JTokenType.Null)]
        private sealed class MStringCase : FilterByValueCase1, ICaseValue<MStringCase, string>
        {
            public string Value;

            public override T Match<T>(
                Func<double, T> precision,
                Func<string, T> mString,
                Func<bool, T> boolean) =>
                   mString != null ? mString(Value) : default;

            public MStringCase Set(string value)
            {
                Value = value;
                return this;
            }

            public string Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is MStringCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<BooleanCase, bool>), JTokenType.Boolean)]
        private sealed class BooleanCase : FilterByValueCase1, ICaseValue<BooleanCase, bool>
        {
            public bool Value;

            public override T Match<T>(
                Func<double, T> precision,
                Func<string, T> mString,
                Func<bool, T> boolean) =>
                   boolean != null ? boolean(Value) : default;

            public BooleanCase Set(bool value)
            {
                Value = value;
                return this;
            }

            public bool Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is BooleanCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value.Equals(other.Value); 
            }
        }
    }
}